/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AAssignStmt extends PAssignStmt
{
    private TIdent _ident_;
    private TAssign _assign_;
    private PExpression _expression_;

    public AAssignStmt()
    {
    }

    public AAssignStmt(
        TIdent _ident_,
        TAssign _assign_,
        PExpression _expression_)
    {
        setIdent(_ident_);

        setAssign(_assign_);

        setExpression(_expression_);

    }
    public Object clone()
    {
        return new AAssignStmt(
            (TIdent) cloneNode(_ident_),
            (TAssign) cloneNode(_assign_),
            (PExpression) cloneNode(_expression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignStmt(this);
    }

    public TIdent getIdent()
    {
        return _ident_;
    }

    public void setIdent(TIdent node)
    {
        if(_ident_ != null)
        {
            _ident_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _ident_ = node;
    }

    public TAssign getAssign()
    {
        return _assign_;
    }

    public void setAssign(TAssign node)
    {
        if(_assign_ != null)
        {
            _assign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _assign_ = node;
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_ident_)
            + toString(_assign_)
            + toString(_expression_);
    }

    void removeChild(Node child)
    {
        if(_ident_ == child)
        {
            _ident_ = null;
            return;
        }

        if(_assign_ == child)
        {
            _assign_ = null;
            return;
        }

        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_ident_ == oldChild)
        {
            setIdent((TIdent) newChild);
            return;
        }

        if(_assign_ == oldChild)
        {
            setAssign((TAssign) newChild);
            return;
        }

        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

    }
}
