/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AAssignmentStatement extends PStatement
{
    private PAssignStmt _assignStmt_;
    private TSemi _semi_;

    public AAssignmentStatement()
    {
    }

    public AAssignmentStatement(
        PAssignStmt _assignStmt_,
        TSemi _semi_)
    {
        setAssignStmt(_assignStmt_);

        setSemi(_semi_);

    }
    public Object clone()
    {
        return new AAssignmentStatement(
            (PAssignStmt) cloneNode(_assignStmt_),
            (TSemi) cloneNode(_semi_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignmentStatement(this);
    }

    public PAssignStmt getAssignStmt()
    {
        return _assignStmt_;
    }

    public void setAssignStmt(PAssignStmt node)
    {
        if(_assignStmt_ != null)
        {
            _assignStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _assignStmt_ = node;
    }

    public TSemi getSemi()
    {
        return _semi_;
    }

    public void setSemi(TSemi node)
    {
        if(_semi_ != null)
        {
            _semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _semi_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_assignStmt_)
            + toString(_semi_);
    }

    void removeChild(Node child)
    {
        if(_assignStmt_ == child)
        {
            _assignStmt_ = null;
            return;
        }

        if(_semi_ == child)
        {
            _semi_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_assignStmt_ == oldChild)
        {
            setAssignStmt((PAssignStmt) newChild);
            return;
        }

        if(_semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

    }
}
