/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AClassDeclaration extends PClassDeclaration
{
    private TPublic _public_;
    private TClas _clas_;
    private TIdent _ident_;
    private TLBrace _lBrace_;
    private final LinkedList _member_ = new TypedLinkedList(new Member_Cast());
    private TRBrace _rBrace_;

    public AClassDeclaration()
    {
    }

    public AClassDeclaration(
        TPublic _public_,
        TClas _clas_,
        TIdent _ident_,
        TLBrace _lBrace_,
        List _member_,
        TRBrace _rBrace_)
    {
        setPublic(_public_);

        setClas(_clas_);

        setIdent(_ident_);

        setLBrace(_lBrace_);

        {
            this._member_.clear();
            this._member_.addAll(_member_);
        }

        setRBrace(_rBrace_);

    }
    public Object clone()
    {
        return new AClassDeclaration(
            (TPublic) cloneNode(_public_),
            (TClas) cloneNode(_clas_),
            (TIdent) cloneNode(_ident_),
            (TLBrace) cloneNode(_lBrace_),
            cloneList(_member_),
            (TRBrace) cloneNode(_rBrace_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClassDeclaration(this);
    }

    public TPublic getPublic()
    {
        return _public_;
    }

    public void setPublic(TPublic node)
    {
        if(_public_ != null)
        {
            _public_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _public_ = node;
    }

    public TClas getClas()
    {
        return _clas_;
    }

    public void setClas(TClas node)
    {
        if(_clas_ != null)
        {
            _clas_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _clas_ = node;
    }

    public TIdent getIdent()
    {
        return _ident_;
    }

    public void setIdent(TIdent node)
    {
        if(_ident_ != null)
        {
            _ident_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _ident_ = node;
    }

    public TLBrace getLBrace()
    {
        return _lBrace_;
    }

    public void setLBrace(TLBrace node)
    {
        if(_lBrace_ != null)
        {
            _lBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lBrace_ = node;
    }

    public LinkedList getMember()
    {
        return _member_;
    }

    public void setMember(List list)
    {
        _member_.clear();
        _member_.addAll(list);
    }

    public TRBrace getRBrace()
    {
        return _rBrace_;
    }

    public void setRBrace(TRBrace node)
    {
        if(_rBrace_ != null)
        {
            _rBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rBrace_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_public_)
            + toString(_clas_)
            + toString(_ident_)
            + toString(_lBrace_)
            + toString(_member_)
            + toString(_rBrace_);
    }

    void removeChild(Node child)
    {
        if(_public_ == child)
        {
            _public_ = null;
            return;
        }

        if(_clas_ == child)
        {
            _clas_ = null;
            return;
        }

        if(_ident_ == child)
        {
            _ident_ = null;
            return;
        }

        if(_lBrace_ == child)
        {
            _lBrace_ = null;
            return;
        }

        if(_member_.remove(child))
        {
            return;
        }

        if(_rBrace_ == child)
        {
            _rBrace_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_public_ == oldChild)
        {
            setPublic((TPublic) newChild);
            return;
        }

        if(_clas_ == oldChild)
        {
            setClas((TClas) newChild);
            return;
        }

        if(_ident_ == oldChild)
        {
            setIdent((TIdent) newChild);
            return;
        }

        if(_lBrace_ == oldChild)
        {
            setLBrace((TLBrace) newChild);
            return;
        }

        for(ListIterator i = _member_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_rBrace_ == oldChild)
        {
            setRBrace((TRBrace) newChild);
            return;
        }

    }

    private class Member_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PMember node = (PMember) o;

            if((node.parent() != null) &&
                (node.parent() != AClassDeclaration.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AClassDeclaration.this))
            {
                node.parent(AClassDeclaration.this);
            }

            return node;
        }
    }
}
