/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class ACondition extends PCondition
{
    private PExpression _left_;
    private TCompare _compare_;
    private PExpression _right_;

    public ACondition()
    {
    }

    public ACondition(
        PExpression _left_,
        TCompare _compare_,
        PExpression _right_)
    {
        setLeft(_left_);

        setCompare(_compare_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new ACondition(
            (PExpression) cloneNode(_left_),
            (TCompare) cloneNode(_compare_),
            (PExpression) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondition(this);
    }

    public PExpression getLeft()
    {
        return _left_;
    }

    public void setLeft(PExpression node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public TCompare getCompare()
    {
        return _compare_;
    }

    public void setCompare(TCompare node)
    {
        if(_compare_ != null)
        {
            _compare_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _compare_ = node;
    }

    public PExpression getRight()
    {
        return _right_;
    }

    public void setRight(PExpression node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_compare_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_compare_ == child)
        {
            _compare_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((PExpression) newChild);
            return;
        }

        if(_compare_ == oldChild)
        {
            setCompare((TCompare) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((PExpression) newChild);
            return;
        }

    }
}
