/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class ADoStatement extends PStatement
{
    private TDo _do_;
    private PBlock _block_;
    private TWhile _while_;
    private TLPar _lPar_;
    private PCondition _condition_;
    private TRPar _rPar_;
    private TSemi _semi_;

    public ADoStatement()
    {
    }

    public ADoStatement(
        TDo _do_,
        PBlock _block_,
        TWhile _while_,
        TLPar _lPar_,
        PCondition _condition_,
        TRPar _rPar_,
        TSemi _semi_)
    {
        setDo(_do_);

        setBlock(_block_);

        setWhile(_while_);

        setLPar(_lPar_);

        setCondition(_condition_);

        setRPar(_rPar_);

        setSemi(_semi_);

    }
    public Object clone()
    {
        return new ADoStatement(
            (TDo) cloneNode(_do_),
            (PBlock) cloneNode(_block_),
            (TWhile) cloneNode(_while_),
            (TLPar) cloneNode(_lPar_),
            (PCondition) cloneNode(_condition_),
            (TRPar) cloneNode(_rPar_),
            (TSemi) cloneNode(_semi_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADoStatement(this);
    }

    public TDo getDo()
    {
        return _do_;
    }

    public void setDo(TDo node)
    {
        if(_do_ != null)
        {
            _do_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _do_ = node;
    }

    public PBlock getBlock()
    {
        return _block_;
    }

    public void setBlock(PBlock node)
    {
        if(_block_ != null)
        {
            _block_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _block_ = node;
    }

    public TWhile getWhile()
    {
        return _while_;
    }

    public void setWhile(TWhile node)
    {
        if(_while_ != null)
        {
            _while_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _while_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PCondition getCondition()
    {
        return _condition_;
    }

    public void setCondition(PCondition node)
    {
        if(_condition_ != null)
        {
            _condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _condition_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public TSemi getSemi()
    {
        return _semi_;
    }

    public void setSemi(TSemi node)
    {
        if(_semi_ != null)
        {
            _semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _semi_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_do_)
            + toString(_block_)
            + toString(_while_)
            + toString(_lPar_)
            + toString(_condition_)
            + toString(_rPar_)
            + toString(_semi_);
    }

    void removeChild(Node child)
    {
        if(_do_ == child)
        {
            _do_ = null;
            return;
        }

        if(_block_ == child)
        {
            _block_ = null;
            return;
        }

        if(_while_ == child)
        {
            _while_ = null;
            return;
        }

        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_condition_ == child)
        {
            _condition_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

        if(_semi_ == child)
        {
            _semi_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_do_ == oldChild)
        {
            setDo((TDo) newChild);
            return;
        }

        if(_block_ == oldChild)
        {
            setBlock((PBlock) newChild);
            return;
        }

        if(_while_ == oldChild)
        {
            setWhile((TWhile) newChild);
            return;
        }

        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_condition_ == oldChild)
        {
            setCondition((PCondition) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        if(_semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

    }
}
