/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AElseClause extends PElseClause
{
    private TElse _else_;
    private PBlock _block_;

    public AElseClause()
    {
    }

    public AElseClause(
        TElse _else_,
        PBlock _block_)
    {
        setElse(_else_);

        setBlock(_block_);

    }
    public Object clone()
    {
        return new AElseClause(
            (TElse) cloneNode(_else_),
            (PBlock) cloneNode(_block_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElseClause(this);
    }

    public TElse getElse()
    {
        return _else_;
    }

    public void setElse(TElse node)
    {
        if(_else_ != null)
        {
            _else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _else_ = node;
    }

    public PBlock getBlock()
    {
        return _block_;
    }

    public void setBlock(PBlock node)
    {
        if(_block_ != null)
        {
            _block_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _block_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_else_)
            + toString(_block_);
    }

    void removeChild(Node child)
    {
        if(_else_ == child)
        {
            _else_ = null;
            return;
        }

        if(_block_ == child)
        {
            _block_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_else_ == oldChild)
        {
            setElse((TElse) newChild);
            return;
        }

        if(_block_ == oldChild)
        {
            setBlock((PBlock) newChild);
            return;
        }

    }
}
