/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AFloatFactor extends PFactor
{
    private TFloatLiteral _floatLiteral_;

    public AFloatFactor()
    {
    }

    public AFloatFactor(
        TFloatLiteral _floatLiteral_)
    {
        setFloatLiteral(_floatLiteral_);

    }
    public Object clone()
    {
        return new AFloatFactor(
            (TFloatLiteral) cloneNode(_floatLiteral_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFloatFactor(this);
    }

    public TFloatLiteral getFloatLiteral()
    {
        return _floatLiteral_;
    }

    public void setFloatLiteral(TFloatLiteral node)
    {
        if(_floatLiteral_ != null)
        {
            _floatLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _floatLiteral_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_floatLiteral_);
    }

    void removeChild(Node child)
    {
        if(_floatLiteral_ == child)
        {
            _floatLiteral_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_floatLiteral_ == oldChild)
        {
            setFloatLiteral((TFloatLiteral) newChild);
            return;
        }

    }
}
