/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AForStatement extends PStatement
{
    private TFor _for_;
    private TLPar _lPar_;
    private PAssignStmt _init_;
    private TSemi _s1_;
    private PCondition _cond_;
    private TSemi _s2_;
    private PAssignStmt _step_;
    private TRPar _rPar_;
    private PBlock _block_;

    public AForStatement()
    {
    }

    public AForStatement(
        TFor _for_,
        TLPar _lPar_,
        PAssignStmt _init_,
        TSemi _s1_,
        PCondition _cond_,
        TSemi _s2_,
        PAssignStmt _step_,
        TRPar _rPar_,
        PBlock _block_)
    {
        setFor(_for_);

        setLPar(_lPar_);

        setInit(_init_);

        setS1(_s1_);

        setCond(_cond_);

        setS2(_s2_);

        setStep(_step_);

        setRPar(_rPar_);

        setBlock(_block_);

    }
    public Object clone()
    {
        return new AForStatement(
            (TFor) cloneNode(_for_),
            (TLPar) cloneNode(_lPar_),
            (PAssignStmt) cloneNode(_init_),
            (TSemi) cloneNode(_s1_),
            (PCondition) cloneNode(_cond_),
            (TSemi) cloneNode(_s2_),
            (PAssignStmt) cloneNode(_step_),
            (TRPar) cloneNode(_rPar_),
            (PBlock) cloneNode(_block_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForStatement(this);
    }

    public TFor getFor()
    {
        return _for_;
    }

    public void setFor(TFor node)
    {
        if(_for_ != null)
        {
            _for_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _for_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PAssignStmt getInit()
    {
        return _init_;
    }

    public void setInit(PAssignStmt node)
    {
        if(_init_ != null)
        {
            _init_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _init_ = node;
    }

    public TSemi getS1()
    {
        return _s1_;
    }

    public void setS1(TSemi node)
    {
        if(_s1_ != null)
        {
            _s1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _s1_ = node;
    }

    public PCondition getCond()
    {
        return _cond_;
    }

    public void setCond(PCondition node)
    {
        if(_cond_ != null)
        {
            _cond_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _cond_ = node;
    }

    public TSemi getS2()
    {
        return _s2_;
    }

    public void setS2(TSemi node)
    {
        if(_s2_ != null)
        {
            _s2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _s2_ = node;
    }

    public PAssignStmt getStep()
    {
        return _step_;
    }

    public void setStep(PAssignStmt node)
    {
        if(_step_ != null)
        {
            _step_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _step_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public PBlock getBlock()
    {
        return _block_;
    }

    public void setBlock(PBlock node)
    {
        if(_block_ != null)
        {
            _block_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _block_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_for_)
            + toString(_lPar_)
            + toString(_init_)
            + toString(_s1_)
            + toString(_cond_)
            + toString(_s2_)
            + toString(_step_)
            + toString(_rPar_)
            + toString(_block_);
    }

    void removeChild(Node child)
    {
        if(_for_ == child)
        {
            _for_ = null;
            return;
        }

        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_init_ == child)
        {
            _init_ = null;
            return;
        }

        if(_s1_ == child)
        {
            _s1_ = null;
            return;
        }

        if(_cond_ == child)
        {
            _cond_ = null;
            return;
        }

        if(_s2_ == child)
        {
            _s2_ = null;
            return;
        }

        if(_step_ == child)
        {
            _step_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

        if(_block_ == child)
        {
            _block_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_for_ == oldChild)
        {
            setFor((TFor) newChild);
            return;
        }

        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_init_ == oldChild)
        {
            setInit((PAssignStmt) newChild);
            return;
        }

        if(_s1_ == oldChild)
        {
            setS1((TSemi) newChild);
            return;
        }

        if(_cond_ == oldChild)
        {
            setCond((PCondition) newChild);
            return;
        }

        if(_s2_ == oldChild)
        {
            setS2((TSemi) newChild);
            return;
        }

        if(_step_ == oldChild)
        {
            setStep((PAssignStmt) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        if(_block_ == oldChild)
        {
            setBlock((PBlock) newChild);
            return;
        }

    }
}
