/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AIfStatement extends PStatement
{
    private TIf _if_;
    private TLPar _lPar_;
    private PCondition _condition_;
    private TRPar _rPar_;
    private PBlock _block_;
    private PElseClause _elseClause_;

    public AIfStatement()
    {
    }

    public AIfStatement(
        TIf _if_,
        TLPar _lPar_,
        PCondition _condition_,
        TRPar _rPar_,
        PBlock _block_,
        PElseClause _elseClause_)
    {
        setIf(_if_);

        setLPar(_lPar_);

        setCondition(_condition_);

        setRPar(_rPar_);

        setBlock(_block_);

        setElseClause(_elseClause_);

    }
    public Object clone()
    {
        return new AIfStatement(
            (TIf) cloneNode(_if_),
            (TLPar) cloneNode(_lPar_),
            (PCondition) cloneNode(_condition_),
            (TRPar) cloneNode(_rPar_),
            (PBlock) cloneNode(_block_),
            (PElseClause) cloneNode(_elseClause_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfStatement(this);
    }

    public TIf getIf()
    {
        return _if_;
    }

    public void setIf(TIf node)
    {
        if(_if_ != null)
        {
            _if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _if_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PCondition getCondition()
    {
        return _condition_;
    }

    public void setCondition(PCondition node)
    {
        if(_condition_ != null)
        {
            _condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _condition_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public PBlock getBlock()
    {
        return _block_;
    }

    public void setBlock(PBlock node)
    {
        if(_block_ != null)
        {
            _block_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _block_ = node;
    }

    public PElseClause getElseClause()
    {
        return _elseClause_;
    }

    public void setElseClause(PElseClause node)
    {
        if(_elseClause_ != null)
        {
            _elseClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _elseClause_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_if_)
            + toString(_lPar_)
            + toString(_condition_)
            + toString(_rPar_)
            + toString(_block_)
            + toString(_elseClause_);
    }

    void removeChild(Node child)
    {
        if(_if_ == child)
        {
            _if_ = null;
            return;
        }

        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_condition_ == child)
        {
            _condition_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

        if(_block_ == child)
        {
            _block_ = null;
            return;
        }

        if(_elseClause_ == child)
        {
            _elseClause_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_condition_ == oldChild)
        {
            setCondition((PCondition) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        if(_block_ == oldChild)
        {
            setBlock((PBlock) newChild);
            return;
        }

        if(_elseClause_ == oldChild)
        {
            setElseClause((PElseClause) newChild);
            return;
        }

    }
}
