/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AIntFactor extends PFactor
{
    private TIntLiteral _intLiteral_;

    public AIntFactor()
    {
    }

    public AIntFactor(
        TIntLiteral _intLiteral_)
    {
        setIntLiteral(_intLiteral_);

    }
    public Object clone()
    {
        return new AIntFactor(
            (TIntLiteral) cloneNode(_intLiteral_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntFactor(this);
    }

    public TIntLiteral getIntLiteral()
    {
        return _intLiteral_;
    }

    public void setIntLiteral(TIntLiteral node)
    {
        if(_intLiteral_ != null)
        {
            _intLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _intLiteral_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_intLiteral_);
    }

    void removeChild(Node child)
    {
        if(_intLiteral_ == child)
        {
            _intLiteral_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_intLiteral_ == oldChild)
        {
            setIntLiteral((TIntLiteral) newChild);
            return;
        }

    }
}
