/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AMethodDeclaration extends PMethodDeclaration
{
    private TPublic _public_;
    private TStatic _static_;
    private PVoidOrType _voidOrType_;
    private TIdent _ident_;
    private TLPar _lPar_;
    private PParameterList _parameterList_;
    private TRPar _rPar_;
    private PBlock _block_;

    public AMethodDeclaration()
    {
    }

    public AMethodDeclaration(
        TPublic _public_,
        TStatic _static_,
        PVoidOrType _voidOrType_,
        TIdent _ident_,
        TLPar _lPar_,
        PParameterList _parameterList_,
        TRPar _rPar_,
        PBlock _block_)
    {
        setPublic(_public_);

        setStatic(_static_);

        setVoidOrType(_voidOrType_);

        setIdent(_ident_);

        setLPar(_lPar_);

        setParameterList(_parameterList_);

        setRPar(_rPar_);

        setBlock(_block_);

    }
    public Object clone()
    {
        return new AMethodDeclaration(
            (TPublic) cloneNode(_public_),
            (TStatic) cloneNode(_static_),
            (PVoidOrType) cloneNode(_voidOrType_),
            (TIdent) cloneNode(_ident_),
            (TLPar) cloneNode(_lPar_),
            (PParameterList) cloneNode(_parameterList_),
            (TRPar) cloneNode(_rPar_),
            (PBlock) cloneNode(_block_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodDeclaration(this);
    }

    public TPublic getPublic()
    {
        return _public_;
    }

    public void setPublic(TPublic node)
    {
        if(_public_ != null)
        {
            _public_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _public_ = node;
    }

    public TStatic getStatic()
    {
        return _static_;
    }

    public void setStatic(TStatic node)
    {
        if(_static_ != null)
        {
            _static_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _static_ = node;
    }

    public PVoidOrType getVoidOrType()
    {
        return _voidOrType_;
    }

    public void setVoidOrType(PVoidOrType node)
    {
        if(_voidOrType_ != null)
        {
            _voidOrType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _voidOrType_ = node;
    }

    public TIdent getIdent()
    {
        return _ident_;
    }

    public void setIdent(TIdent node)
    {
        if(_ident_ != null)
        {
            _ident_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _ident_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PParameterList getParameterList()
    {
        return _parameterList_;
    }

    public void setParameterList(PParameterList node)
    {
        if(_parameterList_ != null)
        {
            _parameterList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _parameterList_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public PBlock getBlock()
    {
        return _block_;
    }

    public void setBlock(PBlock node)
    {
        if(_block_ != null)
        {
            _block_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _block_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_public_)
            + toString(_static_)
            + toString(_voidOrType_)
            + toString(_ident_)
            + toString(_lPar_)
            + toString(_parameterList_)
            + toString(_rPar_)
            + toString(_block_);
    }

    void removeChild(Node child)
    {
        if(_public_ == child)
        {
            _public_ = null;
            return;
        }

        if(_static_ == child)
        {
            _static_ = null;
            return;
        }

        if(_voidOrType_ == child)
        {
            _voidOrType_ = null;
            return;
        }

        if(_ident_ == child)
        {
            _ident_ = null;
            return;
        }

        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_parameterList_ == child)
        {
            _parameterList_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

        if(_block_ == child)
        {
            _block_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_public_ == oldChild)
        {
            setPublic((TPublic) newChild);
            return;
        }

        if(_static_ == oldChild)
        {
            setStatic((TStatic) newChild);
            return;
        }

        if(_voidOrType_ == oldChild)
        {
            setVoidOrType((PVoidOrType) newChild);
            return;
        }

        if(_ident_ == oldChild)
        {
            setIdent((TIdent) newChild);
            return;
        }

        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_parameterList_ == oldChild)
        {
            setParameterList((PParameterList) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        if(_block_ == oldChild)
        {
            setBlock((PBlock) newChild);
            return;
        }

    }
}
