/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AMethodMember extends PMember
{
    private PMethodDeclaration _methodDeclaration_;

    public AMethodMember()
    {
    }

    public AMethodMember(
        PMethodDeclaration _methodDeclaration_)
    {
        setMethodDeclaration(_methodDeclaration_);

    }
    public Object clone()
    {
        return new AMethodMember(
            (PMethodDeclaration) cloneNode(_methodDeclaration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodMember(this);
    }

    public PMethodDeclaration getMethodDeclaration()
    {
        return _methodDeclaration_;
    }

    public void setMethodDeclaration(PMethodDeclaration node)
    {
        if(_methodDeclaration_ != null)
        {
            _methodDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _methodDeclaration_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_methodDeclaration_);
    }

    void removeChild(Node child)
    {
        if(_methodDeclaration_ == child)
        {
            _methodDeclaration_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_methodDeclaration_ == oldChild)
        {
            setMethodDeclaration((PMethodDeclaration) newChild);
            return;
        }

    }
}
