/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AParameterList extends PParameterList
{
    private PType _type_;
    private TIdent _ident_;
    private final LinkedList _parameterRest_ = new TypedLinkedList(new ParameterRest_Cast());

    public AParameterList()
    {
    }

    public AParameterList(
        PType _type_,
        TIdent _ident_,
        List _parameterRest_)
    {
        setType(_type_);

        setIdent(_ident_);

        {
            this._parameterRest_.clear();
            this._parameterRest_.addAll(_parameterRest_);
        }

    }
    public Object clone()
    {
        return new AParameterList(
            (PType) cloneNode(_type_),
            (TIdent) cloneNode(_ident_),
            cloneList(_parameterRest_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParameterList(this);
    }

    public PType getType()
    {
        return _type_;
    }

    public void setType(PType node)
    {
        if(_type_ != null)
        {
            _type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _type_ = node;
    }

    public TIdent getIdent()
    {
        return _ident_;
    }

    public void setIdent(TIdent node)
    {
        if(_ident_ != null)
        {
            _ident_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _ident_ = node;
    }

    public LinkedList getParameterRest()
    {
        return _parameterRest_;
    }

    public void setParameterRest(List list)
    {
        _parameterRest_.clear();
        _parameterRest_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_type_)
            + toString(_ident_)
            + toString(_parameterRest_);
    }

    void removeChild(Node child)
    {
        if(_type_ == child)
        {
            _type_ = null;
            return;
        }

        if(_ident_ == child)
        {
            _ident_ = null;
            return;
        }

        if(_parameterRest_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(_ident_ == oldChild)
        {
            setIdent((TIdent) newChild);
            return;
        }

        for(ListIterator i = _parameterRest_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class ParameterRest_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PParameterRest node = (PParameterRest) o;

            if((node.parent() != null) &&
                (node.parent() != AParameterList.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AParameterList.this))
            {
                node.parent(AParameterList.this);
            }

            return node;
        }
    }
}
