/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class APrintCallStatement extends PStatement
{
    private TMain _main_;
    private TLPar _lPar_;
    private PExpression _expression_;
    private TRPar _rPar_;
    private TSemi _semi_;

    public APrintCallStatement()
    {
    }

    public APrintCallStatement(
        TMain _main_,
        TLPar _lPar_,
        PExpression _expression_,
        TRPar _rPar_,
        TSemi _semi_)
    {
        setMain(_main_);

        setLPar(_lPar_);

        setExpression(_expression_);

        setRPar(_rPar_);

        setSemi(_semi_);

    }
    public Object clone()
    {
        return new APrintCallStatement(
            (TMain) cloneNode(_main_),
            (TLPar) cloneNode(_lPar_),
            (PExpression) cloneNode(_expression_),
            (TRPar) cloneNode(_rPar_),
            (TSemi) cloneNode(_semi_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrintCallStatement(this);
    }

    public TMain getMain()
    {
        return _main_;
    }

    public void setMain(TMain node)
    {
        if(_main_ != null)
        {
            _main_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _main_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public TSemi getSemi()
    {
        return _semi_;
    }

    public void setSemi(TSemi node)
    {
        if(_semi_ != null)
        {
            _semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _semi_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_main_)
            + toString(_lPar_)
            + toString(_expression_)
            + toString(_rPar_)
            + toString(_semi_);
    }

    void removeChild(Node child)
    {
        if(_main_ == child)
        {
            _main_ = null;
            return;
        }

        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

        if(_semi_ == child)
        {
            _semi_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_main_ == oldChild)
        {
            setMain((TMain) newChild);
            return;
        }

        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        if(_semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

    }
}
