/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AProgram extends PProgram
{
    private PClassDeclaration _classDeclaration_;

    public AProgram()
    {
    }

    public AProgram(
        PClassDeclaration _classDeclaration_)
    {
        setClassDeclaration(_classDeclaration_);

    }
    public Object clone()
    {
        return new AProgram(
            (PClassDeclaration) cloneNode(_classDeclaration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public PClassDeclaration getClassDeclaration()
    {
        return _classDeclaration_;
    }

    public void setClassDeclaration(PClassDeclaration node)
    {
        if(_classDeclaration_ != null)
        {
            _classDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _classDeclaration_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_classDeclaration_);
    }

    void removeChild(Node child)
    {
        if(_classDeclaration_ == child)
        {
            _classDeclaration_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_classDeclaration_ == oldChild)
        {
            setClassDeclaration((PClassDeclaration) newChild);
            return;
        }

    }
}
