/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class ATypeVoidOrType extends PVoidOrType
{
    private PType _type_;

    public ATypeVoidOrType()
    {
    }

    public ATypeVoidOrType(
        PType _type_)
    {
        setType(_type_);

    }
    public Object clone()
    {
        return new ATypeVoidOrType(
            (PType) cloneNode(_type_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeVoidOrType(this);
    }

    public PType getType()
    {
        return _type_;
    }

    public void setType(PType node)
    {
        if(_type_ != null)
        {
            _type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _type_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_type_);
    }

    void removeChild(Node child)
    {
        if(_type_ == child)
        {
            _type_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

    }
}
