/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AVariableStatement extends PStatement
{
    private PVariableDeclaration _variableDeclaration_;

    public AVariableStatement()
    {
    }

    public AVariableStatement(
        PVariableDeclaration _variableDeclaration_)
    {
        setVariableDeclaration(_variableDeclaration_);

    }
    public Object clone()
    {
        return new AVariableStatement(
            (PVariableDeclaration) cloneNode(_variableDeclaration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariableStatement(this);
    }

    public PVariableDeclaration getVariableDeclaration()
    {
        return _variableDeclaration_;
    }

    public void setVariableDeclaration(PVariableDeclaration node)
    {
        if(_variableDeclaration_ != null)
        {
            _variableDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _variableDeclaration_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_variableDeclaration_);
    }

    void removeChild(Node child)
    {
        if(_variableDeclaration_ == child)
        {
            _variableDeclaration_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_variableDeclaration_ == oldChild)
        {
            setVariableDeclaration((PVariableDeclaration) newChild);
            return;
        }

    }
}
