/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AVoidVoidOrType extends PVoidOrType
{
    private TVoid _void_;

    public AVoidVoidOrType()
    {
    }

    public AVoidVoidOrType(
        TVoid _void_)
    {
        setVoid(_void_);

    }
    public Object clone()
    {
        return new AVoidVoidOrType(
            (TVoid) cloneNode(_void_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVoidVoidOrType(this);
    }

    public TVoid getVoid()
    {
        return _void_;
    }

    public void setVoid(TVoid node)
    {
        if(_void_ != null)
        {
            _void_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _void_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_void_);
    }

    void removeChild(Node child)
    {
        if(_void_ == child)
        {
            _void_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_void_ == oldChild)
        {
            setVoid((TVoid) newChild);
            return;
        }

    }
}
