/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import java.util.*;
import bahasaManusia.analysis.*;

public final class AWhileStatement extends PStatement
{
    private TWhile _while_;
    private TLPar _lPar_;
    private PCondition _condition_;
    private TRPar _rPar_;
    private PBlock _block_;

    public AWhileStatement()
    {
    }

    public AWhileStatement(
        TWhile _while_,
        TLPar _lPar_,
        PCondition _condition_,
        TRPar _rPar_,
        PBlock _block_)
    {
        setWhile(_while_);

        setLPar(_lPar_);

        setCondition(_condition_);

        setRPar(_rPar_);

        setBlock(_block_);

    }
    public Object clone()
    {
        return new AWhileStatement(
            (TWhile) cloneNode(_while_),
            (TLPar) cloneNode(_lPar_),
            (PCondition) cloneNode(_condition_),
            (TRPar) cloneNode(_rPar_),
            (PBlock) cloneNode(_block_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhileStatement(this);
    }

    public TWhile getWhile()
    {
        return _while_;
    }

    public void setWhile(TWhile node)
    {
        if(_while_ != null)
        {
            _while_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _while_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PCondition getCondition()
    {
        return _condition_;
    }

    public void setCondition(PCondition node)
    {
        if(_condition_ != null)
        {
            _condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _condition_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public PBlock getBlock()
    {
        return _block_;
    }

    public void setBlock(PBlock node)
    {
        if(_block_ != null)
        {
            _block_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _block_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_while_)
            + toString(_lPar_)
            + toString(_condition_)
            + toString(_rPar_)
            + toString(_block_);
    }

    void removeChild(Node child)
    {
        if(_while_ == child)
        {
            _while_ = null;
            return;
        }

        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_condition_ == child)
        {
            _condition_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

        if(_block_ == child)
        {
            _block_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_while_ == oldChild)
        {
            setWhile((TWhile) newChild);
            return;
        }

        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_condition_ == oldChild)
        {
            setCondition((PCondition) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        if(_block_ == oldChild)
        {
            setBlock((PBlock) newChild);
            return;
        }

    }
}
