/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.analysis;

import bahasaManusia.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseStart(Start node);
    void caseAProgram(AProgram node);
    void caseAClassDeclaration(AClassDeclaration node);
    void caseAMethodMember(AMethodMember node);
    void caseAFieldMember(AFieldMember node);
    void caseAMethodDeclaration(AMethodDeclaration node);
    void caseAVoidVoidOrType(AVoidVoidOrType node);
    void caseATypeVoidOrType(ATypeVoidOrType node);
    void caseAIntType(AIntType node);
    void caseAFloatType(AFloatType node);
    void caseAStringType(AStringType node);
    void caseAParameterList(AParameterList node);
    void caseAParameterRest(AParameterRest node);
    void caseABlock(ABlock node);
    void caseAAssignmentStatement(AAssignmentStatement node);
    void caseAVariableStatement(AVariableStatement node);
    void caseAIfStatement(AIfStatement node);
    void caseAWhileStatement(AWhileStatement node);
    void caseADoStatement(ADoStatement node);
    void caseAForStatement(AForStatement node);
    void caseAPrintCallStatement(APrintCallStatement node);
    void caseAAssignStmt(AAssignStmt node);
    void caseAElseClause(AElseClause node);
    void caseAVariableDeclaration(AVariableDeclaration node);
    void caseAAssignValue(AAssignValue node);
    void caseACondition(ACondition node);
    void caseAAddExpression(AAddExpression node);
    void caseASubExpression(ASubExpression node);
    void caseATermExpression(ATermExpression node);
    void caseAMulTerm(AMulTerm node);
    void caseADivTerm(ADivTerm node);
    void caseAFactorTerm(AFactorTerm node);
    void caseAIdFactor(AIdFactor node);
    void caseAIntFactor(AIntFactor node);
    void caseAFloatFactor(AFloatFactor node);
    void caseAGroupedFactor(AGroupedFactor node);

    void caseTComment1(TComment1 node);
    void caseTComment2(TComment2 node);
    void caseTSpace(TSpace node);
    void caseTClas(TClas node);
    void caseTPublic(TPublic node);
    void caseTStatic(TStatic node);
    void caseTVoid(TVoid node);
    void caseTFor(TFor node);
    void caseTDo(TDo node);
    void caseTWhile(TWhile node);
    void caseTIf(TIf node);
    void caseTElse(TElse node);
    void caseTMain(TMain node);
    void caseTInt(TInt node);
    void caseTFloat(TFloat node);
    void caseTString(TString node);
    void caseTAssign(TAssign node);
    void caseTCompare(TCompare node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTLBrace(TLBrace node);
    void caseTRBrace(TRBrace node);
    void caseTLBracket(TLBracket node);
    void caseTRBracket(TRBracket node);
    void caseTSemi(TSemi node);
    void caseTColon(TColon node);
    void caseTComma(TComma node);
    void caseTIdent(TIdent node);
    void caseTIntLiteral(TIntLiteral node);
    void caseTFloatLiteral(TFloatLiteral node);
    void caseTBlank(TBlank node);
    void caseTUnknown(TUnknown node);
    void caseEOF(EOF node);
}
