/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.analysis;

import bahasaManusia.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(Node node)
    {
    }

    public void defaultOut(Node node)
    {
    }

    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPProgram().apply(this);
        outStart(node);
    }

    public void inAProgram(AProgram node)
    {
        defaultIn(node);
    }

    public void outAProgram(AProgram node)
    {
        defaultOut(node);
    }

    public void caseAProgram(AProgram node)
    {
        inAProgram(node);
        if(node.getClassDeclaration() != null)
        {
            node.getClassDeclaration().apply(this);
        }
        outAProgram(node);
    }

    public void inAClassDeclaration(AClassDeclaration node)
    {
        defaultIn(node);
    }

    public void outAClassDeclaration(AClassDeclaration node)
    {
        defaultOut(node);
    }

    public void caseAClassDeclaration(AClassDeclaration node)
    {
        inAClassDeclaration(node);
        if(node.getRBrace() != null)
        {
            node.getRBrace().apply(this);
        }
        {
            Object temp[] = node.getMember().toArray();
            for(int i = temp.length - 1; i >= 0; i--)
            {
                ((PMember) temp[i]).apply(this);
            }
        }
        if(node.getLBrace() != null)
        {
            node.getLBrace().apply(this);
        }
        if(node.getIdent() != null)
        {
            node.getIdent().apply(this);
        }
        if(node.getClas() != null)
        {
            node.getClas().apply(this);
        }
        if(node.getPublic() != null)
        {
            node.getPublic().apply(this);
        }
        outAClassDeclaration(node);
    }

    public void inAMethodMember(AMethodMember node)
    {
        defaultIn(node);
    }

    public void outAMethodMember(AMethodMember node)
    {
        defaultOut(node);
    }

    public void caseAMethodMember(AMethodMember node)
    {
        inAMethodMember(node);
        if(node.getMethodDeclaration() != null)
        {
            node.getMethodDeclaration().apply(this);
        }
        outAMethodMember(node);
    }

    public void inAFieldMember(AFieldMember node)
    {
        defaultIn(node);
    }

    public void outAFieldMember(AFieldMember node)
    {
        defaultOut(node);
    }

    public void caseAFieldMember(AFieldMember node)
    {
        inAFieldMember(node);
        if(node.getVariableDeclaration() != null)
        {
            node.getVariableDeclaration().apply(this);
        }
        outAFieldMember(node);
    }

    public void inAMethodDeclaration(AMethodDeclaration node)
    {
        defaultIn(node);
    }

    public void outAMethodDeclaration(AMethodDeclaration node)
    {
        defaultOut(node);
    }

    public void caseAMethodDeclaration(AMethodDeclaration node)
    {
        inAMethodDeclaration(node);
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getParameterList() != null)
        {
            node.getParameterList().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getIdent() != null)
        {
            node.getIdent().apply(this);
        }
        if(node.getVoidOrType() != null)
        {
            node.getVoidOrType().apply(this);
        }
        if(node.getStatic() != null)
        {
            node.getStatic().apply(this);
        }
        if(node.getPublic() != null)
        {
            node.getPublic().apply(this);
        }
        outAMethodDeclaration(node);
    }

    public void inAVoidVoidOrType(AVoidVoidOrType node)
    {
        defaultIn(node);
    }

    public void outAVoidVoidOrType(AVoidVoidOrType node)
    {
        defaultOut(node);
    }

    public void caseAVoidVoidOrType(AVoidVoidOrType node)
    {
        inAVoidVoidOrType(node);
        if(node.getVoid() != null)
        {
            node.getVoid().apply(this);
        }
        outAVoidVoidOrType(node);
    }

    public void inATypeVoidOrType(ATypeVoidOrType node)
    {
        defaultIn(node);
    }

    public void outATypeVoidOrType(ATypeVoidOrType node)
    {
        defaultOut(node);
    }

    public void caseATypeVoidOrType(ATypeVoidOrType node)
    {
        inATypeVoidOrType(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outATypeVoidOrType(node);
    }

    public void inAIntType(AIntType node)
    {
        defaultIn(node);
    }

    public void outAIntType(AIntType node)
    {
        defaultOut(node);
    }

    public void caseAIntType(AIntType node)
    {
        inAIntType(node);
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        outAIntType(node);
    }

    public void inAFloatType(AFloatType node)
    {
        defaultIn(node);
    }

    public void outAFloatType(AFloatType node)
    {
        defaultOut(node);
    }

    public void caseAFloatType(AFloatType node)
    {
        inAFloatType(node);
        if(node.getFloat() != null)
        {
            node.getFloat().apply(this);
        }
        outAFloatType(node);
    }

    public void inAStringType(AStringType node)
    {
        defaultIn(node);
    }

    public void outAStringType(AStringType node)
    {
        defaultOut(node);
    }

    public void caseAStringType(AStringType node)
    {
        inAStringType(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAStringType(node);
    }

    public void inAParameterList(AParameterList node)
    {
        defaultIn(node);
    }

    public void outAParameterList(AParameterList node)
    {
        defaultOut(node);
    }

    public void caseAParameterList(AParameterList node)
    {
        inAParameterList(node);
        {
            Object temp[] = node.getParameterRest().toArray();
            for(int i = temp.length - 1; i >= 0; i--)
            {
                ((PParameterRest) temp[i]).apply(this);
            }
        }
        if(node.getIdent() != null)
        {
            node.getIdent().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outAParameterList(node);
    }

    public void inAParameterRest(AParameterRest node)
    {
        defaultIn(node);
    }

    public void outAParameterRest(AParameterRest node)
    {
        defaultOut(node);
    }

    public void caseAParameterRest(AParameterRest node)
    {
        inAParameterRest(node);
        if(node.getIdent() != null)
        {
            node.getIdent().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        outAParameterRest(node);
    }

    public void inABlock(ABlock node)
    {
        defaultIn(node);
    }

    public void outABlock(ABlock node)
    {
        defaultOut(node);
    }

    public void caseABlock(ABlock node)
    {
        inABlock(node);
        if(node.getRBrace() != null)
        {
            node.getRBrace().apply(this);
        }
        {
            Object temp[] = node.getStatement().toArray();
            for(int i = temp.length - 1; i >= 0; i--)
            {
                ((PStatement) temp[i]).apply(this);
            }
        }
        if(node.getLBrace() != null)
        {
            node.getLBrace().apply(this);
        }
        outABlock(node);
    }

    public void inAAssignmentStatement(AAssignmentStatement node)
    {
        defaultIn(node);
    }

    public void outAAssignmentStatement(AAssignmentStatement node)
    {
        defaultOut(node);
    }

    public void caseAAssignmentStatement(AAssignmentStatement node)
    {
        inAAssignmentStatement(node);
        if(node.getSemi() != null)
        {
            node.getSemi().apply(this);
        }
        if(node.getAssignStmt() != null)
        {
            node.getAssignStmt().apply(this);
        }
        outAAssignmentStatement(node);
    }

    public void inAVariableStatement(AVariableStatement node)
    {
        defaultIn(node);
    }

    public void outAVariableStatement(AVariableStatement node)
    {
        defaultOut(node);
    }

    public void caseAVariableStatement(AVariableStatement node)
    {
        inAVariableStatement(node);
        if(node.getVariableDeclaration() != null)
        {
            node.getVariableDeclaration().apply(this);
        }
        outAVariableStatement(node);
    }

    public void inAIfStatement(AIfStatement node)
    {
        defaultIn(node);
    }

    public void outAIfStatement(AIfStatement node)
    {
        defaultOut(node);
    }

    public void caseAIfStatement(AIfStatement node)
    {
        inAIfStatement(node);
        if(node.getElseClause() != null)
        {
            node.getElseClause().apply(this);
        }
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        outAIfStatement(node);
    }

    public void inAWhileStatement(AWhileStatement node)
    {
        defaultIn(node);
    }

    public void outAWhileStatement(AWhileStatement node)
    {
        defaultOut(node);
    }

    public void caseAWhileStatement(AWhileStatement node)
    {
        inAWhileStatement(node);
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getWhile() != null)
        {
            node.getWhile().apply(this);
        }
        outAWhileStatement(node);
    }

    public void inADoStatement(ADoStatement node)
    {
        defaultIn(node);
    }

    public void outADoStatement(ADoStatement node)
    {
        defaultOut(node);
    }

    public void caseADoStatement(ADoStatement node)
    {
        inADoStatement(node);
        if(node.getSemi() != null)
        {
            node.getSemi().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getWhile() != null)
        {
            node.getWhile().apply(this);
        }
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        outADoStatement(node);
    }

    public void inAForStatement(AForStatement node)
    {
        defaultIn(node);
    }

    public void outAForStatement(AForStatement node)
    {
        defaultOut(node);
    }

    public void caseAForStatement(AForStatement node)
    {
        inAForStatement(node);
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getStep() != null)
        {
            node.getStep().apply(this);
        }
        if(node.getS2() != null)
        {
            node.getS2().apply(this);
        }
        if(node.getCond() != null)
        {
            node.getCond().apply(this);
        }
        if(node.getS1() != null)
        {
            node.getS1().apply(this);
        }
        if(node.getInit() != null)
        {
            node.getInit().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getFor() != null)
        {
            node.getFor().apply(this);
        }
        outAForStatement(node);
    }

    public void inAPrintCallStatement(APrintCallStatement node)
    {
        defaultIn(node);
    }

    public void outAPrintCallStatement(APrintCallStatement node)
    {
        defaultOut(node);
    }

    public void caseAPrintCallStatement(APrintCallStatement node)
    {
        inAPrintCallStatement(node);
        if(node.getSemi() != null)
        {
            node.getSemi().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getMain() != null)
        {
            node.getMain().apply(this);
        }
        outAPrintCallStatement(node);
    }

    public void inAAssignStmt(AAssignStmt node)
    {
        defaultIn(node);
    }

    public void outAAssignStmt(AAssignStmt node)
    {
        defaultOut(node);
    }

    public void caseAAssignStmt(AAssignStmt node)
    {
        inAAssignStmt(node);
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getAssign() != null)
        {
            node.getAssign().apply(this);
        }
        if(node.getIdent() != null)
        {
            node.getIdent().apply(this);
        }
        outAAssignStmt(node);
    }

    public void inAElseClause(AElseClause node)
    {
        defaultIn(node);
    }

    public void outAElseClause(AElseClause node)
    {
        defaultOut(node);
    }

    public void caseAElseClause(AElseClause node)
    {
        inAElseClause(node);
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        outAElseClause(node);
    }

    public void inAVariableDeclaration(AVariableDeclaration node)
    {
        defaultIn(node);
    }

    public void outAVariableDeclaration(AVariableDeclaration node)
    {
        defaultOut(node);
    }

    public void caseAVariableDeclaration(AVariableDeclaration node)
    {
        inAVariableDeclaration(node);
        if(node.getSemi() != null)
        {
            node.getSemi().apply(this);
        }
        if(node.getAssignValue() != null)
        {
            node.getAssignValue().apply(this);
        }
        if(node.getIdent() != null)
        {
            node.getIdent().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outAVariableDeclaration(node);
    }

    public void inAAssignValue(AAssignValue node)
    {
        defaultIn(node);
    }

    public void outAAssignValue(AAssignValue node)
    {
        defaultOut(node);
    }

    public void caseAAssignValue(AAssignValue node)
    {
        inAAssignValue(node);
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getAssign() != null)
        {
            node.getAssign().apply(this);
        }
        outAAssignValue(node);
    }

    public void inACondition(ACondition node)
    {
        defaultIn(node);
    }

    public void outACondition(ACondition node)
    {
        defaultOut(node);
    }

    public void caseACondition(ACondition node)
    {
        inACondition(node);
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        if(node.getCompare() != null)
        {
            node.getCompare().apply(this);
        }
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        outACondition(node);
    }

    public void inAAddExpression(AAddExpression node)
    {
        defaultIn(node);
    }

    public void outAAddExpression(AAddExpression node)
    {
        defaultOut(node);
    }

    public void caseAAddExpression(AAddExpression node)
    {
        inAAddExpression(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAAddExpression(node);
    }

    public void inASubExpression(ASubExpression node)
    {
        defaultIn(node);
    }

    public void outASubExpression(ASubExpression node)
    {
        defaultOut(node);
    }

    public void caseASubExpression(ASubExpression node)
    {
        inASubExpression(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outASubExpression(node);
    }

    public void inATermExpression(ATermExpression node)
    {
        defaultIn(node);
    }

    public void outATermExpression(ATermExpression node)
    {
        defaultOut(node);
    }

    public void caseATermExpression(ATermExpression node)
    {
        inATermExpression(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outATermExpression(node);
    }

    public void inAMulTerm(AMulTerm node)
    {
        defaultIn(node);
    }

    public void outAMulTerm(AMulTerm node)
    {
        defaultOut(node);
    }

    public void caseAMulTerm(AMulTerm node)
    {
        inAMulTerm(node);
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        if(node.getMult() != null)
        {
            node.getMult().apply(this);
        }
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outAMulTerm(node);
    }

    public void inADivTerm(ADivTerm node)
    {
        defaultIn(node);
    }

    public void outADivTerm(ADivTerm node)
    {
        defaultOut(node);
    }

    public void caseADivTerm(ADivTerm node)
    {
        inADivTerm(node);
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outADivTerm(node);
    }

    public void inAFactorTerm(AFactorTerm node)
    {
        defaultIn(node);
    }

    public void outAFactorTerm(AFactorTerm node)
    {
        defaultOut(node);
    }

    public void caseAFactorTerm(AFactorTerm node)
    {
        inAFactorTerm(node);
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        outAFactorTerm(node);
    }

    public void inAIdFactor(AIdFactor node)
    {
        defaultIn(node);
    }

    public void outAIdFactor(AIdFactor node)
    {
        defaultOut(node);
    }

    public void caseAIdFactor(AIdFactor node)
    {
        inAIdFactor(node);
        if(node.getIdent() != null)
        {
            node.getIdent().apply(this);
        }
        outAIdFactor(node);
    }

    public void inAIntFactor(AIntFactor node)
    {
        defaultIn(node);
    }

    public void outAIntFactor(AIntFactor node)
    {
        defaultOut(node);
    }

    public void caseAIntFactor(AIntFactor node)
    {
        inAIntFactor(node);
        if(node.getIntLiteral() != null)
        {
            node.getIntLiteral().apply(this);
        }
        outAIntFactor(node);
    }

    public void inAFloatFactor(AFloatFactor node)
    {
        defaultIn(node);
    }

    public void outAFloatFactor(AFloatFactor node)
    {
        defaultOut(node);
    }

    public void caseAFloatFactor(AFloatFactor node)
    {
        inAFloatFactor(node);
        if(node.getFloatLiteral() != null)
        {
            node.getFloatLiteral().apply(this);
        }
        outAFloatFactor(node);
    }

    public void inAGroupedFactor(AGroupedFactor node)
    {
        defaultIn(node);
    }

    public void outAGroupedFactor(AGroupedFactor node)
    {
        defaultOut(node);
    }

    public void caseAGroupedFactor(AGroupedFactor node)
    {
        inAGroupedFactor(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        outAGroupedFactor(node);
    }
}
