/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura.analysis;

import sakura.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseTSakura(TSakura node);
    void caseTHana(THana node);
    void caseTMain(TMain node);
    void caseTSeisu(TSeisu node);
    void caseTJissuu(TJissuu node);
    void caseTTame(TTame node);
    void caseTAida(TAida node);
    void caseTShikashi(TShikashi node);
    void caseTMoshi(TMoshi node);
    void caseTSoretomo(TSoretomo node);
    void caseTBegin(TBegin node);
    void caseTEnd(TEnd node);
    void caseTAssign(TAssign node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTLe(TLe node);
    void caseTGe(TGe node);
    void caseTLt(TLt node);
    void caseTGt(TGt node);
    void caseTEq(TEq node);
    void caseTLparen(TLparen node);
    void caseTRparen(TRparen node);
    void caseTSemi(TSemi node);
    void caseTComma(TComma node);
    void caseTNumber(TNumber node);
    void caseTIdentifier(TIdentifier node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
}
