/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura_VOD.lexer;

import java.io.*;
import java.util.*;
import sakura_VOD.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(int line, int pos) { return new TSakura(line, pos); }
    Token new1(int line, int pos) { return new THana(line, pos); }
    Token new2(int line, int pos) { return new TMain(line, pos); }
    Token new3(int line, int pos) { return new TSeisu(line, pos); }
    Token new4(int line, int pos) { return new TJissuu(line, pos); }
    Token new5(int line, int pos) { return new TTame(line, pos); }
    Token new6(int line, int pos) { return new TAida(line, pos); }
    Token new7(int line, int pos) { return new TShikashi(line, pos); }
    Token new8(int line, int pos) { return new TMoshi(line, pos); }
    Token new9(int line, int pos) { return new TSoretomo(line, pos); }
    Token new10(int line, int pos) { return new TBegin(line, pos); }
    Token new11(int line, int pos) { return new TEnd(line, pos); }
    Token new12(int line, int pos) { return new TAssign(line, pos); }
    Token new13(int line, int pos) { return new TPlus(line, pos); }
    Token new14(int line, int pos) { return new TMinus(line, pos); }
    Token new15(int line, int pos) { return new TMult(line, pos); }
    Token new16(int line, int pos) { return new TDiv(line, pos); }
    Token new17(int line, int pos) { return new TLe(line, pos); }
    Token new18(int line, int pos) { return new TGe(line, pos); }
    Token new19(int line, int pos) { return new TLt(line, pos); }
    Token new20(int line, int pos) { return new TGt(line, pos); }
    Token new21(int line, int pos) { return new TEq(line, pos); }
    Token new22(int line, int pos) { return new TLparen(line, pos); }
    Token new23(int line, int pos) { return new TRparen(line, pos); }
    Token new24(int line, int pos) { return new TSemi(line, pos); }
    Token new25(int line, int pos) { return new TComma(line, pos); }
    Token new26(String text, int line, int pos) { return new TNumber(text, line, pos); }
    Token new27(String text, int line, int pos) { return new TIdentifier(text, line, pos); }
    Token new28(String text, int line, int pos) { return new TBlank(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{32, 32, 1}, {40, 40, 2}, {41, 41, 3}, {42, 42, 4}, {43, 43, 5}, {44, 44, 6}, {45, 45, 7}, {47, 47, 8}, {48, 57, 9}, {59, 59, 10}, {60, 60, 11}, {61, 61, 12}, {62, 62, 13}, {65, 90, 14}, {92, 92, 15}, {97, 97, 16}, {98, 98, 17}, {99, 104, 18}, {105, 105, 19}, {106, 106, 20}, {107, 108, 18}, {109, 109, 21}, {110, 111, 18}, {112, 112, 22}, {113, 114, 18}, {115, 115, 23}, {116, 116, 24}, {117, 117, 25}, {118, 122, 18}, },
            {{32, 32, 1}, {92, 92, 15}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{46, 46, 26}, {48, 57, 9}, },
            {},
            {{45, 45, 27}, {61, 61, 28}, },
            {{61, 61, 29}, },
            {{61, 61, 30}, },
            {{48, 57, 31}, {65, 90, 32}, {97, 122, 33}, },
            {{110, 110, 34}, {114, 114, 35}, {116, 116, 36}, },
            {{48, 90, -16}, {97, 115, 33}, {116, 116, 37}, {117, 122, 33}, },
            {{48, 90, -16}, {97, 116, 33}, {117, 117, 38}, {118, 122, 33}, },
            {{48, 122, -16}, },
            {{48, 90, -16}, {97, 109, 33}, {110, 110, 39}, {111, 122, 33}, },
            {{48, 90, -16}, {97, 104, 33}, {105, 105, 40}, {106, 122, 33}, },
            {{48, 116, -19}, {117, 117, 41}, {118, 122, 33}, },
            {{48, 90, -16}, {97, 100, 33}, {101, 101, 42}, {102, 122, 33}, },
            {{48, 90, -16}, {97, 97, 43}, {98, 100, 33}, {101, 101, 44}, {102, 122, 33}, },
            {{48, 90, -16}, {97, 97, 45}, {98, 122, 33}, },
            {{48, 109, -21}, {110, 110, 46}, {111, 115, 33}, {116, 116, 47}, {117, 122, 33}, },
            {{48, 57, 48}, },
            {},
            {},
            {},
            {},
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{32, 92, -3}, },
            {{32, 92, -3}, },
            {{32, 92, -3}, },
            {{48, 90, -16}, {97, 97, 49}, {98, 122, 33}, },
            {{48, 109, -21}, {110, 110, 50}, {111, 122, 33}, },
            {{48, 115, -18}, {116, 116, 51}, {117, 122, 33}, },
            {{48, 90, -16}, {97, 106, 33}, {107, 107, 52}, {108, 122, 33}, },
            {{48, 90, -16}, {97, 107, 33}, {108, 108, 53}, {109, 122, 33}, },
            {{48, 90, -16}, {97, 113, 33}, {114, 114, 54}, {115, 122, 33}, },
            {{48, 106, -42}, {107, 107, 55}, {108, 122, 33}, },
            {{48, 107, -43}, {108, 108, 56}, {109, 122, 33}, },
            {{48, 90, -16}, {97, 108, 33}, {109, 109, 57}, {110, 122, 33}, },
            {{48, 115, -18}, {116, 116, 58}, {117, 122, 33}, },
            {{48, 90, -16}, {97, 97, 59}, {98, 122, 33}, },
            {{48, 57, 48}, },
            {{48, 116, -19}, {117, 117, 60}, {118, 122, 33}, },
            {{48, 90, -16}, {97, 102, 33}, {103, 103, 61}, {104, 122, 33}, },
            {{48, 100, -24}, {101, 101, 62}, {102, 122, 33}, },
            {{48, 90, -16}, {97, 97, 63}, {98, 122, 33}, },
            {{48, 90, -16}, {97, 97, 64}, {98, 122, 33}, },
            {{48, 90, -16}, {97, 111, 33}, {112, 112, 65}, {113, 122, 33}, },
            {{48, 116, -19}, {117, 117, 66}, {118, 122, 33}, },
            {{48, 90, -16}, {97, 97, 67}, {98, 122, 33}, },
            {{48, 90, -16}, {97, 97, 68}, {98, 122, 33}, },
            {{48, 116, -19}, {117, 117, 69}, {118, 122, 33}, },
            {{48, 108, -47}, {109, 109, 70}, {110, 122, 33}, },
            {{48, 111, -56}, {112, 112, 71}, {113, 122, 33}, },
            {{48, 90, -16}, {97, 97, 72}, {98, 122, 33}, },
            {{48, 102, -52}, {103, 103, 73}, {104, 122, 33}, },
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{48, 116, -19}, {117, 117, 74}, {118, 122, 33}, },
            {{48, 113, -44}, {114, 114, 75}, {115, 122, 33}, },
            {{48, 102, -52}, {103, 103, 76}, {104, 104, 33}, {105, 105, 77}, {106, 122, 33}, },
            {{48, 115, -18}, {116, 116, 78}, {117, 122, 33}, },
            {{48, 106, -42}, {107, 107, 79}, {108, 122, 33}, },
            {{48, 90, -16}, {97, 97, 80}, {98, 122, 33}, },
            {{48, 116, -19}, {117, 117, 81}, {118, 122, 33}, },
            {{48, 122, -16}, },
            {{48, 100, -24}, {101, 101, 82}, {102, 122, 33}, },
            {{48, 107, -43}, {108, 108, 83}, {109, 122, 33}, },
            {{48, 90, -16}, {97, 97, 84}, {98, 122, 33}, },
            {{48, 104, -22}, {105, 105, 85}, {106, 122, 33}, },
            {{48, 109, -21}, {110, 110, 86}, {111, 122, 33}, },
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{48, 109, -21}, {110, 110, 87}, {111, 122, 33}, },
            {{48, 113, -44}, {114, 114, 88}, {115, 122, 33}, },
            {{48, 116, -19}, {117, 117, 89}, {118, 122, 33}, },
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{48, 90, -16}, {97, 103, 33}, {104, 104, 90}, {105, 122, 33}, },
            {{48, 90, -16}, {97, 97, 91}, {98, 122, 33}, },
            {{48, 109, -21}, {110, 110, 92}, {111, 122, 33}, },
            {{48, 122, -16}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 28, 22, 23, 15, 13, 25, 14, 16, 26, 24, 19, -1, 20, 27, -1, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, -1, 12, 17, 21, 18, 27, 27, 27, 28, 28, 28, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 8, 10, 27, 27, 27, 27, 27, 27, 27, 1, 27, 27, 27, 27, 27, 11, 5, 2, 27, 27, 27, 0, 6, 7, 9, 3, 27, 27, 27, 4, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
