/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.node;

import bahasaManusia.analysis.*;

public final class TIntLiteral extends Token
{
    public TIntLiteral(String text)
    {
        setText(text);
    }

    public TIntLiteral(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TIntLiteral(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIntLiteral(this);
    }
}
