/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.parser;

import bahasaManusia.lexer.*;
import bahasaManusia.node.*;
import bahasaManusia.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;
    }

    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);
        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {
                    case 0: /* reduce AProgram */
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;
                    case 1: /* reduce AAclassdeclaration1ClassDeclaration */
		    {
			ArrayList list = new1();
			push(goTo(1), list);
		    }
		    break;
                    case 2: /* reduce AAclassdeclaration2ClassDeclaration */
		    {
			ArrayList list = new2();
			push(goTo(1), list);
		    }
		    break;
                    case 3: /* reduce AAclassdeclaration3ClassDeclaration */
		    {
			ArrayList list = new3();
			push(goTo(1), list);
		    }
		    break;
                    case 4: /* reduce AAclassdeclaration4ClassDeclaration */
		    {
			ArrayList list = new4();
			push(goTo(1), list);
		    }
		    break;
                    case 5: /* reduce AMethodMember */
		    {
			ArrayList list = new5();
			push(goTo(2), list);
		    }
		    break;
                    case 6: /* reduce AFieldMember */
		    {
			ArrayList list = new6();
			push(goTo(2), list);
		    }
		    break;
                    case 7: /* reduce AAmethoddeclaration1$Void1MethodDeclaration */
		    {
			ArrayList list = new7();
			push(goTo(3), list);
		    }
		    break;
                    case 8: /* reduce AAmethoddeclaration1$Type1MethodDeclaration */
		    {
			ArrayList list = new8();
			push(goTo(3), list);
		    }
		    break;
                    case 9: /* reduce AAmethoddeclaration2$Void1MethodDeclaration */
		    {
			ArrayList list = new9();
			push(goTo(3), list);
		    }
		    break;
                    case 10: /* reduce AAmethoddeclaration2$Type1MethodDeclaration */
		    {
			ArrayList list = new10();
			push(goTo(3), list);
		    }
		    break;
                    case 11: /* reduce AAmethoddeclaration3$Void1MethodDeclaration */
		    {
			ArrayList list = new11();
			push(goTo(3), list);
		    }
		    break;
                    case 12: /* reduce AAmethoddeclaration3$Type1MethodDeclaration */
		    {
			ArrayList list = new12();
			push(goTo(3), list);
		    }
		    break;
                    case 13: /* reduce AAmethoddeclaration4$Void1MethodDeclaration */
		    {
			ArrayList list = new13();
			push(goTo(3), list);
		    }
		    break;
                    case 14: /* reduce AAmethoddeclaration4$Type1MethodDeclaration */
		    {
			ArrayList list = new14();
			push(goTo(3), list);
		    }
		    break;
                    case 15: /* reduce AAmethoddeclaration5$Void1MethodDeclaration */
		    {
			ArrayList list = new15();
			push(goTo(3), list);
		    }
		    break;
                    case 16: /* reduce AAmethoddeclaration5$Type1MethodDeclaration */
		    {
			ArrayList list = new16();
			push(goTo(3), list);
		    }
		    break;
                    case 17: /* reduce AAmethoddeclaration6$Void1MethodDeclaration */
		    {
			ArrayList list = new17();
			push(goTo(3), list);
		    }
		    break;
                    case 18: /* reduce AAmethoddeclaration6$Type1MethodDeclaration */
		    {
			ArrayList list = new18();
			push(goTo(3), list);
		    }
		    break;
                    case 19: /* reduce AAmethoddeclaration7$Void1MethodDeclaration */
		    {
			ArrayList list = new19();
			push(goTo(3), list);
		    }
		    break;
                    case 20: /* reduce AAmethoddeclaration7$Type1MethodDeclaration */
		    {
			ArrayList list = new20();
			push(goTo(3), list);
		    }
		    break;
                    case 21: /* reduce AAmethoddeclaration8$Void1MethodDeclaration */
		    {
			ArrayList list = new21();
			push(goTo(3), list);
		    }
		    break;
                    case 22: /* reduce AAmethoddeclaration8$Type1MethodDeclaration */
		    {
			ArrayList list = new22();
			push(goTo(3), list);
		    }
		    break;
                    case 23: /* reduce AIntType */
		    {
			ArrayList list = new23();
			push(goTo(4), list);
		    }
		    break;
                    case 24: /* reduce AFloatType */
		    {
			ArrayList list = new24();
			push(goTo(4), list);
		    }
		    break;
                    case 25: /* reduce AStringType */
		    {
			ArrayList list = new25();
			push(goTo(4), list);
		    }
		    break;
                    case 26: /* reduce AAparameterlist1ParameterList */
		    {
			ArrayList list = new26();
			push(goTo(5), list);
		    }
		    break;
                    case 27: /* reduce AAparameterlist2ParameterList */
		    {
			ArrayList list = new27();
			push(goTo(5), list);
		    }
		    break;
                    case 28: /* reduce AParameterRest */
		    {
			ArrayList list = new28();
			push(goTo(6), list);
		    }
		    break;
                    case 29: /* reduce AAblock1Block */
		    {
			ArrayList list = new29();
			push(goTo(7), list);
		    }
		    break;
                    case 30: /* reduce AAblock2Block */
		    {
			ArrayList list = new30();
			push(goTo(7), list);
		    }
		    break;
                    case 31: /* reduce AAssignmentStatement */
		    {
			ArrayList list = new31();
			push(goTo(8), list);
		    }
		    break;
                    case 32: /* reduce AVariableStatement */
		    {
			ArrayList list = new32();
			push(goTo(8), list);
		    }
		    break;
                    case 33: /* reduce AAifstatement1Statement */
		    {
			ArrayList list = new33();
			push(goTo(8), list);
		    }
		    break;
                    case 34: /* reduce AAifstatement2Statement */
		    {
			ArrayList list = new34();
			push(goTo(8), list);
		    }
		    break;
                    case 35: /* reduce AWhileStatement */
		    {
			ArrayList list = new35();
			push(goTo(8), list);
		    }
		    break;
                    case 36: /* reduce ADoStatement */
		    {
			ArrayList list = new36();
			push(goTo(8), list);
		    }
		    break;
                    case 37: /* reduce AForStatement */
		    {
			ArrayList list = new37();
			push(goTo(8), list);
		    }
		    break;
                    case 38: /* reduce APrintCallStatement */
		    {
			ArrayList list = new38();
			push(goTo(8), list);
		    }
		    break;
                    case 39: /* reduce AAssignStmt */
		    {
			ArrayList list = new39();
			push(goTo(9), list);
		    }
		    break;
                    case 40: /* reduce AElseClause */
		    {
			ArrayList list = new40();
			push(goTo(10), list);
		    }
		    break;
                    case 41: /* reduce AAvariabledeclaration1VariableDeclaration */
		    {
			ArrayList list = new41();
			push(goTo(11), list);
		    }
		    break;
                    case 42: /* reduce AAvariabledeclaration2VariableDeclaration */
		    {
			ArrayList list = new42();
			push(goTo(11), list);
		    }
		    break;
                    case 43: /* reduce AAssignValue */
		    {
			ArrayList list = new43();
			push(goTo(12), list);
		    }
		    break;
                    case 44: /* reduce ACondition */
		    {
			ArrayList list = new44();
			push(goTo(13), list);
		    }
		    break;
                    case 45: /* reduce AAddExpression */
		    {
			ArrayList list = new45();
			push(goTo(14), list);
		    }
		    break;
                    case 46: /* reduce ASubExpression */
		    {
			ArrayList list = new46();
			push(goTo(14), list);
		    }
		    break;
                    case 47: /* reduce ATermExpression */
		    {
			ArrayList list = new47();
			push(goTo(14), list);
		    }
		    break;
                    case 48: /* reduce AMulTerm */
		    {
			ArrayList list = new48();
			push(goTo(15), list);
		    }
		    break;
                    case 49: /* reduce ADivTerm */
		    {
			ArrayList list = new49();
			push(goTo(15), list);
		    }
		    break;
                    case 50: /* reduce AFactorTerm */
		    {
			ArrayList list = new50();
			push(goTo(15), list);
		    }
		    break;
                    case 51: /* reduce AIdFactor */
		    {
			ArrayList list = new51();
			push(goTo(16), list);
		    }
		    break;
                    case 52: /* reduce AIntFactor */
		    {
			ArrayList list = new52();
			push(goTo(16), list);
		    }
		    break;
                    case 53: /* reduce AFloatFactor */
		    {
			ArrayList list = new53();
			push(goTo(16), list);
		    }
		    break;
                    case 54: /* reduce AGroupedFactor */
		    {
			ArrayList list = new54();
			push(goTo(16), list);
		    }
		    break;
                    case 55: /* reduce ATerminal$Member */
		    {
			ArrayList list = new55();
			push(goTo(17), list);
		    }
		    break;
                    case 56: /* reduce ANonTerminal$Member */
		    {
			ArrayList list = new56();
			push(goTo(17), list);
		    }
		    break;
                    case 57: /* reduce ATerminal$ParameterRest */
		    {
			ArrayList list = new57();
			push(goTo(18), list);
		    }
		    break;
                    case 58: /* reduce ANonTerminal$ParameterRest */
		    {
			ArrayList list = new58();
			push(goTo(18), list);
		    }
		    break;
                    case 59: /* reduce ATerminal$Statement */
		    {
			ArrayList list = new59();
			push(goTo(19), list);
		    }
		    break;
                    case 60: /* reduce ANonTerminal$Statement */
		    {
			ArrayList list = new60();
			push(goTo(19), list);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PProgram node1 = (PProgram) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0() /* reduce AProgram */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PProgram pprogramNode1;
        {
        PClassDeclaration pclassdeclarationNode2;
        pclassdeclarationNode2 = (PClassDeclaration)nodeArrayList1.get(0);

        pprogramNode1 = new AProgram(pclassdeclarationNode2);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    ArrayList new1() /* reduce AAclassdeclaration1ClassDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PClassDeclaration pclassdeclarationNode1;
        {
        Object nullNode2 = null;
        TClas tclasNode3;
        TIdent tidentNode4;
        TLBrace tlbraceNode5;
        TypedLinkedList listNode6 = new TypedLinkedList();
        TRBrace trbraceNode7;
        tclasNode3 = (TClas)nodeArrayList1.get(0);
        tidentNode4 = (TIdent)nodeArrayList2.get(0);
        tlbraceNode5 = (TLBrace)nodeArrayList3.get(0);
        {
        }
        trbraceNode7 = (TRBrace)nodeArrayList4.get(0);

        pclassdeclarationNode1 = new AClassDeclaration(null, tclasNode3, tidentNode4, tlbraceNode5, listNode6, trbraceNode7);
        }
	nodeList.add(pclassdeclarationNode1);
        return nodeList;
    }



    ArrayList new2() /* reduce AAclassdeclaration2ClassDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PClassDeclaration pclassdeclarationNode1;
        {
        TPublic tpublicNode2;
        TClas tclasNode3;
        TIdent tidentNode4;
        TLBrace tlbraceNode5;
        TypedLinkedList listNode6 = new TypedLinkedList();
        TRBrace trbraceNode7;
        tpublicNode2 = (TPublic)nodeArrayList1.get(0);
        tclasNode3 = (TClas)nodeArrayList2.get(0);
        tidentNode4 = (TIdent)nodeArrayList3.get(0);
        tlbraceNode5 = (TLBrace)nodeArrayList4.get(0);
        {
        }
        trbraceNode7 = (TRBrace)nodeArrayList5.get(0);

        pclassdeclarationNode1 = new AClassDeclaration(tpublicNode2, tclasNode3, tidentNode4, tlbraceNode5, listNode6, trbraceNode7);
        }
	nodeList.add(pclassdeclarationNode1);
        return nodeList;
    }



    ArrayList new3() /* reduce AAclassdeclaration3ClassDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PClassDeclaration pclassdeclarationNode1;
        {
        Object nullNode2 = null;
        TClas tclasNode3;
        TIdent tidentNode4;
        TLBrace tlbraceNode5;
        TypedLinkedList listNode7 = new TypedLinkedList();
        TRBrace trbraceNode8;
        tclasNode3 = (TClas)nodeArrayList1.get(0);
        tidentNode4 = (TIdent)nodeArrayList2.get(0);
        tlbraceNode5 = (TLBrace)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode6 = new TypedLinkedList();
        listNode6 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }
        trbraceNode8 = (TRBrace)nodeArrayList5.get(0);

        pclassdeclarationNode1 = new AClassDeclaration(null, tclasNode3, tidentNode4, tlbraceNode5, listNode7, trbraceNode8);
        }
	nodeList.add(pclassdeclarationNode1);
        return nodeList;
    }



    ArrayList new4() /* reduce AAclassdeclaration4ClassDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PClassDeclaration pclassdeclarationNode1;
        {
        TPublic tpublicNode2;
        TClas tclasNode3;
        TIdent tidentNode4;
        TLBrace tlbraceNode5;
        TypedLinkedList listNode7 = new TypedLinkedList();
        TRBrace trbraceNode8;
        tpublicNode2 = (TPublic)nodeArrayList1.get(0);
        tclasNode3 = (TClas)nodeArrayList2.get(0);
        tidentNode4 = (TIdent)nodeArrayList3.get(0);
        tlbraceNode5 = (TLBrace)nodeArrayList4.get(0);
        {
        TypedLinkedList listNode6 = new TypedLinkedList();
        listNode6 = (TypedLinkedList)nodeArrayList5.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }
        trbraceNode8 = (TRBrace)nodeArrayList6.get(0);

        pclassdeclarationNode1 = new AClassDeclaration(tpublicNode2, tclasNode3, tidentNode4, tlbraceNode5, listNode7, trbraceNode8);
        }
	nodeList.add(pclassdeclarationNode1);
        return nodeList;
    }



    ArrayList new5() /* reduce AMethodMember */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMember pmemberNode1;
        {
        PMethodDeclaration pmethoddeclarationNode2;
        pmethoddeclarationNode2 = (PMethodDeclaration)nodeArrayList1.get(0);

        pmemberNode1 = new AMethodMember(pmethoddeclarationNode2);
        }
	nodeList.add(pmemberNode1);
        return nodeList;
    }



    ArrayList new6() /* reduce AFieldMember */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMember pmemberNode1;
        {
        PVariableDeclaration pvariabledeclarationNode2;
        pvariabledeclarationNode2 = (PVariableDeclaration)nodeArrayList1.get(0);

        pmemberNode1 = new AFieldMember(pvariabledeclarationNode2);
        }
	nodeList.add(pmemberNode1);
        return nodeList;
    }



    ArrayList new7() /* reduce AAmethoddeclaration1$Void1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        Object nullNode2 = null;
        Object nullNode3 = null;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        Object nullNode8 = null;
        TRPar trparNode9;
        PBlock pblockNode10;
        {
        TVoid tvoidNode5;
        tvoidNode5 = (TVoid)nodeArrayList1.get(0);

        pvoidortypeNode4 = new AVoidVoidOrType(tvoidNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList2.get(0);
        tlparNode7 = (TLPar)nodeArrayList3.get(0);
        trparNode9 = (TRPar)nodeArrayList4.get(0);
        pblockNode10 = (PBlock)nodeArrayList5.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(null, null, pvoidortypeNode4, tidentNode6, tlparNode7, null, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new8() /* reduce AAmethoddeclaration1$Type1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        Object nullNode2 = null;
        Object nullNode3 = null;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        Object nullNode8 = null;
        TRPar trparNode9;
        PBlock pblockNode10;
        {
        PType ptypeNode5;
        ptypeNode5 = (PType)nodeArrayList1.get(0);

        pvoidortypeNode4 = new ATypeVoidOrType(ptypeNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList2.get(0);
        tlparNode7 = (TLPar)nodeArrayList3.get(0);
        trparNode9 = (TRPar)nodeArrayList4.get(0);
        pblockNode10 = (PBlock)nodeArrayList5.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(null, null, pvoidortypeNode4, tidentNode6, tlparNode7, null, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new9() /* reduce AAmethoddeclaration2$Void1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        TPublic tpublicNode2;
        Object nullNode3 = null;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        Object nullNode8 = null;
        TRPar trparNode9;
        PBlock pblockNode10;
        tpublicNode2 = (TPublic)nodeArrayList1.get(0);
        {
        TVoid tvoidNode5;
        tvoidNode5 = (TVoid)nodeArrayList2.get(0);

        pvoidortypeNode4 = new AVoidVoidOrType(tvoidNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList3.get(0);
        tlparNode7 = (TLPar)nodeArrayList4.get(0);
        trparNode9 = (TRPar)nodeArrayList5.get(0);
        pblockNode10 = (PBlock)nodeArrayList6.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(tpublicNode2, null, pvoidortypeNode4, tidentNode6, tlparNode7, null, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new10() /* reduce AAmethoddeclaration2$Type1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        TPublic tpublicNode2;
        Object nullNode3 = null;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        Object nullNode8 = null;
        TRPar trparNode9;
        PBlock pblockNode10;
        tpublicNode2 = (TPublic)nodeArrayList1.get(0);
        {
        PType ptypeNode5;
        ptypeNode5 = (PType)nodeArrayList2.get(0);

        pvoidortypeNode4 = new ATypeVoidOrType(ptypeNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList3.get(0);
        tlparNode7 = (TLPar)nodeArrayList4.get(0);
        trparNode9 = (TRPar)nodeArrayList5.get(0);
        pblockNode10 = (PBlock)nodeArrayList6.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(tpublicNode2, null, pvoidortypeNode4, tidentNode6, tlparNode7, null, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new11() /* reduce AAmethoddeclaration3$Void1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        Object nullNode2 = null;
        TStatic tstaticNode3;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        Object nullNode8 = null;
        TRPar trparNode9;
        PBlock pblockNode10;
        tstaticNode3 = (TStatic)nodeArrayList1.get(0);
        {
        TVoid tvoidNode5;
        tvoidNode5 = (TVoid)nodeArrayList2.get(0);

        pvoidortypeNode4 = new AVoidVoidOrType(tvoidNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList3.get(0);
        tlparNode7 = (TLPar)nodeArrayList4.get(0);
        trparNode9 = (TRPar)nodeArrayList5.get(0);
        pblockNode10 = (PBlock)nodeArrayList6.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(null, tstaticNode3, pvoidortypeNode4, tidentNode6, tlparNode7, null, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new12() /* reduce AAmethoddeclaration3$Type1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        Object nullNode2 = null;
        TStatic tstaticNode3;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        Object nullNode8 = null;
        TRPar trparNode9;
        PBlock pblockNode10;
        tstaticNode3 = (TStatic)nodeArrayList1.get(0);
        {
        PType ptypeNode5;
        ptypeNode5 = (PType)nodeArrayList2.get(0);

        pvoidortypeNode4 = new ATypeVoidOrType(ptypeNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList3.get(0);
        tlparNode7 = (TLPar)nodeArrayList4.get(0);
        trparNode9 = (TRPar)nodeArrayList5.get(0);
        pblockNode10 = (PBlock)nodeArrayList6.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(null, tstaticNode3, pvoidortypeNode4, tidentNode6, tlparNode7, null, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new13() /* reduce AAmethoddeclaration4$Void1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        TPublic tpublicNode2;
        TStatic tstaticNode3;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        Object nullNode8 = null;
        TRPar trparNode9;
        PBlock pblockNode10;
        tpublicNode2 = (TPublic)nodeArrayList1.get(0);
        tstaticNode3 = (TStatic)nodeArrayList2.get(0);
        {
        TVoid tvoidNode5;
        tvoidNode5 = (TVoid)nodeArrayList3.get(0);

        pvoidortypeNode4 = new AVoidVoidOrType(tvoidNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList4.get(0);
        tlparNode7 = (TLPar)nodeArrayList5.get(0);
        trparNode9 = (TRPar)nodeArrayList6.get(0);
        pblockNode10 = (PBlock)nodeArrayList7.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(tpublicNode2, tstaticNode3, pvoidortypeNode4, tidentNode6, tlparNode7, null, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new14() /* reduce AAmethoddeclaration4$Type1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        TPublic tpublicNode2;
        TStatic tstaticNode3;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        Object nullNode8 = null;
        TRPar trparNode9;
        PBlock pblockNode10;
        tpublicNode2 = (TPublic)nodeArrayList1.get(0);
        tstaticNode3 = (TStatic)nodeArrayList2.get(0);
        {
        PType ptypeNode5;
        ptypeNode5 = (PType)nodeArrayList3.get(0);

        pvoidortypeNode4 = new ATypeVoidOrType(ptypeNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList4.get(0);
        tlparNode7 = (TLPar)nodeArrayList5.get(0);
        trparNode9 = (TRPar)nodeArrayList6.get(0);
        pblockNode10 = (PBlock)nodeArrayList7.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(tpublicNode2, tstaticNode3, pvoidortypeNode4, tidentNode6, tlparNode7, null, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new15() /* reduce AAmethoddeclaration5$Void1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        Object nullNode2 = null;
        Object nullNode3 = null;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        PParameterList pparameterlistNode8;
        TRPar trparNode9;
        PBlock pblockNode10;
        {
        TVoid tvoidNode5;
        tvoidNode5 = (TVoid)nodeArrayList1.get(0);

        pvoidortypeNode4 = new AVoidVoidOrType(tvoidNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList2.get(0);
        tlparNode7 = (TLPar)nodeArrayList3.get(0);
        pparameterlistNode8 = (PParameterList)nodeArrayList4.get(0);
        trparNode9 = (TRPar)nodeArrayList5.get(0);
        pblockNode10 = (PBlock)nodeArrayList6.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(null, null, pvoidortypeNode4, tidentNode6, tlparNode7, pparameterlistNode8, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new16() /* reduce AAmethoddeclaration5$Type1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        Object nullNode2 = null;
        Object nullNode3 = null;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        PParameterList pparameterlistNode8;
        TRPar trparNode9;
        PBlock pblockNode10;
        {
        PType ptypeNode5;
        ptypeNode5 = (PType)nodeArrayList1.get(0);

        pvoidortypeNode4 = new ATypeVoidOrType(ptypeNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList2.get(0);
        tlparNode7 = (TLPar)nodeArrayList3.get(0);
        pparameterlistNode8 = (PParameterList)nodeArrayList4.get(0);
        trparNode9 = (TRPar)nodeArrayList5.get(0);
        pblockNode10 = (PBlock)nodeArrayList6.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(null, null, pvoidortypeNode4, tidentNode6, tlparNode7, pparameterlistNode8, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new17() /* reduce AAmethoddeclaration6$Void1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        TPublic tpublicNode2;
        Object nullNode3 = null;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        PParameterList pparameterlistNode8;
        TRPar trparNode9;
        PBlock pblockNode10;
        tpublicNode2 = (TPublic)nodeArrayList1.get(0);
        {
        TVoid tvoidNode5;
        tvoidNode5 = (TVoid)nodeArrayList2.get(0);

        pvoidortypeNode4 = new AVoidVoidOrType(tvoidNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList3.get(0);
        tlparNode7 = (TLPar)nodeArrayList4.get(0);
        pparameterlistNode8 = (PParameterList)nodeArrayList5.get(0);
        trparNode9 = (TRPar)nodeArrayList6.get(0);
        pblockNode10 = (PBlock)nodeArrayList7.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(tpublicNode2, null, pvoidortypeNode4, tidentNode6, tlparNode7, pparameterlistNode8, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new18() /* reduce AAmethoddeclaration6$Type1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        TPublic tpublicNode2;
        Object nullNode3 = null;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        PParameterList pparameterlistNode8;
        TRPar trparNode9;
        PBlock pblockNode10;
        tpublicNode2 = (TPublic)nodeArrayList1.get(0);
        {
        PType ptypeNode5;
        ptypeNode5 = (PType)nodeArrayList2.get(0);

        pvoidortypeNode4 = new ATypeVoidOrType(ptypeNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList3.get(0);
        tlparNode7 = (TLPar)nodeArrayList4.get(0);
        pparameterlistNode8 = (PParameterList)nodeArrayList5.get(0);
        trparNode9 = (TRPar)nodeArrayList6.get(0);
        pblockNode10 = (PBlock)nodeArrayList7.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(tpublicNode2, null, pvoidortypeNode4, tidentNode6, tlparNode7, pparameterlistNode8, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new19() /* reduce AAmethoddeclaration7$Void1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        Object nullNode2 = null;
        TStatic tstaticNode3;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        PParameterList pparameterlistNode8;
        TRPar trparNode9;
        PBlock pblockNode10;
        tstaticNode3 = (TStatic)nodeArrayList1.get(0);
        {
        TVoid tvoidNode5;
        tvoidNode5 = (TVoid)nodeArrayList2.get(0);

        pvoidortypeNode4 = new AVoidVoidOrType(tvoidNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList3.get(0);
        tlparNode7 = (TLPar)nodeArrayList4.get(0);
        pparameterlistNode8 = (PParameterList)nodeArrayList5.get(0);
        trparNode9 = (TRPar)nodeArrayList6.get(0);
        pblockNode10 = (PBlock)nodeArrayList7.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(null, tstaticNode3, pvoidortypeNode4, tidentNode6, tlparNode7, pparameterlistNode8, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new20() /* reduce AAmethoddeclaration7$Type1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        Object nullNode2 = null;
        TStatic tstaticNode3;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        PParameterList pparameterlistNode8;
        TRPar trparNode9;
        PBlock pblockNode10;
        tstaticNode3 = (TStatic)nodeArrayList1.get(0);
        {
        PType ptypeNode5;
        ptypeNode5 = (PType)nodeArrayList2.get(0);

        pvoidortypeNode4 = new ATypeVoidOrType(ptypeNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList3.get(0);
        tlparNode7 = (TLPar)nodeArrayList4.get(0);
        pparameterlistNode8 = (PParameterList)nodeArrayList5.get(0);
        trparNode9 = (TRPar)nodeArrayList6.get(0);
        pblockNode10 = (PBlock)nodeArrayList7.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(null, tstaticNode3, pvoidortypeNode4, tidentNode6, tlparNode7, pparameterlistNode8, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new21() /* reduce AAmethoddeclaration8$Void1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList8 = (ArrayList) pop();
        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        TPublic tpublicNode2;
        TStatic tstaticNode3;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        PParameterList pparameterlistNode8;
        TRPar trparNode9;
        PBlock pblockNode10;
        tpublicNode2 = (TPublic)nodeArrayList1.get(0);
        tstaticNode3 = (TStatic)nodeArrayList2.get(0);
        {
        TVoid tvoidNode5;
        tvoidNode5 = (TVoid)nodeArrayList3.get(0);

        pvoidortypeNode4 = new AVoidVoidOrType(tvoidNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList4.get(0);
        tlparNode7 = (TLPar)nodeArrayList5.get(0);
        pparameterlistNode8 = (PParameterList)nodeArrayList6.get(0);
        trparNode9 = (TRPar)nodeArrayList7.get(0);
        pblockNode10 = (PBlock)nodeArrayList8.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(tpublicNode2, tstaticNode3, pvoidortypeNode4, tidentNode6, tlparNode7, pparameterlistNode8, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new22() /* reduce AAmethoddeclaration8$Type1MethodDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList8 = (ArrayList) pop();
        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMethodDeclaration pmethoddeclarationNode1;
        {
        TPublic tpublicNode2;
        TStatic tstaticNode3;
        PVoidOrType pvoidortypeNode4;
        TIdent tidentNode6;
        TLPar tlparNode7;
        PParameterList pparameterlistNode8;
        TRPar trparNode9;
        PBlock pblockNode10;
        tpublicNode2 = (TPublic)nodeArrayList1.get(0);
        tstaticNode3 = (TStatic)nodeArrayList2.get(0);
        {
        PType ptypeNode5;
        ptypeNode5 = (PType)nodeArrayList3.get(0);

        pvoidortypeNode4 = new ATypeVoidOrType(ptypeNode5);
        }
        tidentNode6 = (TIdent)nodeArrayList4.get(0);
        tlparNode7 = (TLPar)nodeArrayList5.get(0);
        pparameterlistNode8 = (PParameterList)nodeArrayList6.get(0);
        trparNode9 = (TRPar)nodeArrayList7.get(0);
        pblockNode10 = (PBlock)nodeArrayList8.get(0);

        pmethoddeclarationNode1 = new AMethodDeclaration(tpublicNode2, tstaticNode3, pvoidortypeNode4, tidentNode6, tlparNode7, pparameterlistNode8, trparNode9, pblockNode10);
        }
	nodeList.add(pmethoddeclarationNode1);
        return nodeList;
    }



    ArrayList new23() /* reduce AIntType */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PType ptypeNode1;
        {
        TInt tintNode2;
        tintNode2 = (TInt)nodeArrayList1.get(0);

        ptypeNode1 = new AIntType(tintNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    ArrayList new24() /* reduce AFloatType */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PType ptypeNode1;
        {
        TFloat tfloatNode2;
        tfloatNode2 = (TFloat)nodeArrayList1.get(0);

        ptypeNode1 = new AFloatType(tfloatNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    ArrayList new25() /* reduce AStringType */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PType ptypeNode1;
        {
        TString tstringNode2;
        tstringNode2 = (TString)nodeArrayList1.get(0);

        ptypeNode1 = new AStringType(tstringNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    ArrayList new26() /* reduce AAparameterlist1ParameterList */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PParameterList pparameterlistNode1;
        {
        PType ptypeNode2;
        TIdent tidentNode3;
        TypedLinkedList listNode4 = new TypedLinkedList();
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tidentNode3 = (TIdent)nodeArrayList2.get(0);
        {
        }

        pparameterlistNode1 = new AParameterList(ptypeNode2, tidentNode3, listNode4);
        }
	nodeList.add(pparameterlistNode1);
        return nodeList;
    }



    ArrayList new27() /* reduce AAparameterlist2ParameterList */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PParameterList pparameterlistNode1;
        {
        PType ptypeNode2;
        TIdent tidentNode3;
        TypedLinkedList listNode5 = new TypedLinkedList();
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tidentNode3 = (TIdent)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pparameterlistNode1 = new AParameterList(ptypeNode2, tidentNode3, listNode5);
        }
	nodeList.add(pparameterlistNode1);
        return nodeList;
    }



    ArrayList new28() /* reduce AParameterRest */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PParameterRest pparameterrestNode1;
        {
        TComma tcommaNode2;
        PType ptypeNode3;
        TIdent tidentNode4;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        ptypeNode3 = (PType)nodeArrayList2.get(0);
        tidentNode4 = (TIdent)nodeArrayList3.get(0);

        pparameterrestNode1 = new AParameterRest(tcommaNode2, ptypeNode3, tidentNode4);
        }
	nodeList.add(pparameterrestNode1);
        return nodeList;
    }



    ArrayList new29() /* reduce AAblock1Block */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PBlock pblockNode1;
        {
        TLBrace tlbraceNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        TRBrace trbraceNode4;
        tlbraceNode2 = (TLBrace)nodeArrayList1.get(0);
        {
        }
        trbraceNode4 = (TRBrace)nodeArrayList2.get(0);

        pblockNode1 = new ABlock(tlbraceNode2, listNode3, trbraceNode4);
        }
	nodeList.add(pblockNode1);
        return nodeList;
    }



    ArrayList new30() /* reduce AAblock2Block */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PBlock pblockNode1;
        {
        TLBrace tlbraceNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        TRBrace trbraceNode5;
        tlbraceNode2 = (TLBrace)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        trbraceNode5 = (TRBrace)nodeArrayList3.get(0);

        pblockNode1 = new ABlock(tlbraceNode2, listNode4, trbraceNode5);
        }
	nodeList.add(pblockNode1);
        return nodeList;
    }



    ArrayList new31() /* reduce AAssignmentStatement */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PAssignStmt passignstmtNode2;
        TSemi tsemiNode3;
        passignstmtNode2 = (PAssignStmt)nodeArrayList1.get(0);
        tsemiNode3 = (TSemi)nodeArrayList2.get(0);

        pstatementNode1 = new AAssignmentStatement(passignstmtNode2, tsemiNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new32() /* reduce AVariableStatement */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PVariableDeclaration pvariabledeclarationNode2;
        pvariabledeclarationNode2 = (PVariableDeclaration)nodeArrayList1.get(0);

        pstatementNode1 = new AVariableStatement(pvariabledeclarationNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new33() /* reduce AAifstatement1Statement */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TIf tifNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        PBlock pblockNode6;
        Object nullNode7 = null;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        pblockNode6 = (PBlock)nodeArrayList5.get(0);

        pstatementNode1 = new AIfStatement(tifNode2, tlparNode3, pconditionNode4, trparNode5, pblockNode6, null);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new34() /* reduce AAifstatement2Statement */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TIf tifNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        PBlock pblockNode6;
        PElseClause pelseclauseNode7;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        pblockNode6 = (PBlock)nodeArrayList5.get(0);
        pelseclauseNode7 = (PElseClause)nodeArrayList6.get(0);

        pstatementNode1 = new AIfStatement(tifNode2, tlparNode3, pconditionNode4, trparNode5, pblockNode6, pelseclauseNode7);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new35() /* reduce AWhileStatement */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TWhile twhileNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        PBlock pblockNode6;
        twhileNode2 = (TWhile)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        pblockNode6 = (PBlock)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatement(twhileNode2, tlparNode3, pconditionNode4, trparNode5, pblockNode6);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new36() /* reduce ADoStatement */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TDo tdoNode2;
        PBlock pblockNode3;
        TWhile twhileNode4;
        TLPar tlparNode5;
        PCondition pconditionNode6;
        TRPar trparNode7;
        TSemi tsemiNode8;
        tdoNode2 = (TDo)nodeArrayList1.get(0);
        pblockNode3 = (PBlock)nodeArrayList2.get(0);
        twhileNode4 = (TWhile)nodeArrayList3.get(0);
        tlparNode5 = (TLPar)nodeArrayList4.get(0);
        pconditionNode6 = (PCondition)nodeArrayList5.get(0);
        trparNode7 = (TRPar)nodeArrayList6.get(0);
        tsemiNode8 = (TSemi)nodeArrayList7.get(0);

        pstatementNode1 = new ADoStatement(tdoNode2, pblockNode3, twhileNode4, tlparNode5, pconditionNode6, trparNode7, tsemiNode8);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new37() /* reduce AForStatement */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList9 = (ArrayList) pop();
        ArrayList nodeArrayList8 = (ArrayList) pop();
        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TFor tforNode2;
        TLPar tlparNode3;
        PAssignStmt passignstmtNode4;
        TSemi tsemiNode5;
        PCondition pconditionNode6;
        TSemi tsemiNode7;
        PAssignStmt passignstmtNode8;
        TRPar trparNode9;
        PBlock pblockNode10;
        tforNode2 = (TFor)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        passignstmtNode4 = (PAssignStmt)nodeArrayList3.get(0);
        tsemiNode5 = (TSemi)nodeArrayList4.get(0);
        pconditionNode6 = (PCondition)nodeArrayList5.get(0);
        tsemiNode7 = (TSemi)nodeArrayList6.get(0);
        passignstmtNode8 = (PAssignStmt)nodeArrayList7.get(0);
        trparNode9 = (TRPar)nodeArrayList8.get(0);
        pblockNode10 = (PBlock)nodeArrayList9.get(0);

        pstatementNode1 = new AForStatement(tforNode2, tlparNode3, passignstmtNode4, tsemiNode5, pconditionNode6, tsemiNode7, passignstmtNode8, trparNode9, pblockNode10);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new38() /* reduce APrintCallStatement */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TMain tmainNode2;
        TLPar tlparNode3;
        PExpression pexpressionNode4;
        TRPar trparNode5;
        TSemi tsemiNode6;
        tmainNode2 = (TMain)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tsemiNode6 = (TSemi)nodeArrayList5.get(0);

        pstatementNode1 = new APrintCallStatement(tmainNode2, tlparNode3, pexpressionNode4, trparNode5, tsemiNode6);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new39() /* reduce AAssignStmt */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PAssignStmt passignstmtNode1;
        {
        TIdent tidentNode2;
        TAssign tassignNode3;
        PExpression pexpressionNode4;
        tidentNode2 = (TIdent)nodeArrayList1.get(0);
        tassignNode3 = (TAssign)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);

        passignstmtNode1 = new AAssignStmt(tidentNode2, tassignNode3, pexpressionNode4);
        }
	nodeList.add(passignstmtNode1);
        return nodeList;
    }



    ArrayList new40() /* reduce AElseClause */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PElseClause pelseclauseNode1;
        {
        TElse telseNode2;
        PBlock pblockNode3;
        telseNode2 = (TElse)nodeArrayList1.get(0);
        pblockNode3 = (PBlock)nodeArrayList2.get(0);

        pelseclauseNode1 = new AElseClause(telseNode2, pblockNode3);
        }
	nodeList.add(pelseclauseNode1);
        return nodeList;
    }



    ArrayList new41() /* reduce AAvariabledeclaration1VariableDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PVariableDeclaration pvariabledeclarationNode1;
        {
        PType ptypeNode2;
        TIdent tidentNode3;
        Object nullNode4 = null;
        TSemi tsemiNode5;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tidentNode3 = (TIdent)nodeArrayList2.get(0);
        tsemiNode5 = (TSemi)nodeArrayList3.get(0);

        pvariabledeclarationNode1 = new AVariableDeclaration(ptypeNode2, tidentNode3, null, tsemiNode5);
        }
	nodeList.add(pvariabledeclarationNode1);
        return nodeList;
    }



    ArrayList new42() /* reduce AAvariabledeclaration2VariableDeclaration */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PVariableDeclaration pvariabledeclarationNode1;
        {
        PType ptypeNode2;
        TIdent tidentNode3;
        PAssignValue passignvalueNode4;
        TSemi tsemiNode5;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tidentNode3 = (TIdent)nodeArrayList2.get(0);
        passignvalueNode4 = (PAssignValue)nodeArrayList3.get(0);
        tsemiNode5 = (TSemi)nodeArrayList4.get(0);

        pvariabledeclarationNode1 = new AVariableDeclaration(ptypeNode2, tidentNode3, passignvalueNode4, tsemiNode5);
        }
	nodeList.add(pvariabledeclarationNode1);
        return nodeList;
    }



    ArrayList new43() /* reduce AAssignValue */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PAssignValue passignvalueNode1;
        {
        TAssign tassignNode2;
        PExpression pexpressionNode3;
        tassignNode2 = (TAssign)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList2.get(0);

        passignvalueNode1 = new AAssignValue(tassignNode2, pexpressionNode3);
        }
	nodeList.add(passignvalueNode1);
        return nodeList;
    }



    ArrayList new44() /* reduce ACondition */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCondition pconditionNode1;
        {
        PExpression pexpressionNode2;
        TCompare tcompareNode3;
        PExpression pexpressionNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tcompareNode3 = (TCompare)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);

        pconditionNode1 = new ACondition(pexpressionNode2, tcompareNode3, pexpressionNode4);
        }
	nodeList.add(pconditionNode1);
        return nodeList;
    }



    ArrayList new45() /* reduce AAddExpression */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        TPlus tplusNode3;
        PTerm ptermNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tplusNode3 = (TPlus)nodeArrayList2.get(0);
        ptermNode4 = (PTerm)nodeArrayList3.get(0);

        pexpressionNode1 = new AAddExpression(pexpressionNode2, tplusNode3, ptermNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new46() /* reduce ASubExpression */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        TMinus tminusNode3;
        PTerm ptermNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tminusNode3 = (TMinus)nodeArrayList2.get(0);
        ptermNode4 = (PTerm)nodeArrayList3.get(0);

        pexpressionNode1 = new ASubExpression(pexpressionNode2, tminusNode3, ptermNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new47() /* reduce ATermExpression */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PTerm ptermNode2;
        ptermNode2 = (PTerm)nodeArrayList1.get(0);

        pexpressionNode1 = new ATermExpression(ptermNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new48() /* reduce AMulTerm */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PTerm ptermNode1;
        {
        PTerm ptermNode2;
        TMult tmultNode3;
        PFactor pfactorNode4;
        ptermNode2 = (PTerm)nodeArrayList1.get(0);
        tmultNode3 = (TMult)nodeArrayList2.get(0);
        pfactorNode4 = (PFactor)nodeArrayList3.get(0);

        ptermNode1 = new AMulTerm(ptermNode2, tmultNode3, pfactorNode4);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    ArrayList new49() /* reduce ADivTerm */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PTerm ptermNode1;
        {
        PTerm ptermNode2;
        TDiv tdivNode3;
        PFactor pfactorNode4;
        ptermNode2 = (PTerm)nodeArrayList1.get(0);
        tdivNode3 = (TDiv)nodeArrayList2.get(0);
        pfactorNode4 = (PFactor)nodeArrayList3.get(0);

        ptermNode1 = new ADivTerm(ptermNode2, tdivNode3, pfactorNode4);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    ArrayList new50() /* reduce AFactorTerm */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PTerm ptermNode1;
        {
        PFactor pfactorNode2;
        pfactorNode2 = (PFactor)nodeArrayList1.get(0);

        ptermNode1 = new AFactorTerm(pfactorNode2);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    ArrayList new51() /* reduce AIdFactor */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFactor pfactorNode1;
        {
        TIdent tidentNode2;
        tidentNode2 = (TIdent)nodeArrayList1.get(0);

        pfactorNode1 = new AIdFactor(tidentNode2);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    ArrayList new52() /* reduce AIntFactor */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFactor pfactorNode1;
        {
        TIntLiteral tintliteralNode2;
        tintliteralNode2 = (TIntLiteral)nodeArrayList1.get(0);

        pfactorNode1 = new AIntFactor(tintliteralNode2);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    ArrayList new53() /* reduce AFloatFactor */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFactor pfactorNode1;
        {
        TFloatLiteral tfloatliteralNode2;
        tfloatliteralNode2 = (TFloatLiteral)nodeArrayList1.get(0);

        pfactorNode1 = new AFloatFactor(tfloatliteralNode2);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    ArrayList new54() /* reduce AGroupedFactor */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFactor pfactorNode1;
        {
        TLPar tlparNode2;
        PExpression pexpressionNode3;
        TRPar trparNode4;
        tlparNode2 = (TLPar)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList2.get(0);
        trparNode4 = (TRPar)nodeArrayList3.get(0);

        pfactorNode1 = new AGroupedFactor(tlparNode2, pexpressionNode3, trparNode4);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    ArrayList new55() /* reduce ATerminal$Member */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PMember pmemberNode1;
        pmemberNode1 = (PMember)nodeArrayList1.get(0);
	if(pmemberNode1 != null)
	{
	  listNode2.add(pmemberNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new56() /* reduce ANonTerminal$Member */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PMember pmemberNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pmemberNode2 = (PMember)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmemberNode2 != null)
	{
	  listNode3.add(pmemberNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new57() /* reduce ATerminal$ParameterRest */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PParameterRest pparameterrestNode1;
        pparameterrestNode1 = (PParameterRest)nodeArrayList1.get(0);
	if(pparameterrestNode1 != null)
	{
	  listNode2.add(pparameterrestNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new58() /* reduce ANonTerminal$ParameterRest */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PParameterRest pparameterrestNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pparameterrestNode2 = (PParameterRest)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pparameterrestNode2 != null)
	{
	  listNode3.add(pparameterrestNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new59() /* reduce ATerminal$Statement */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PStatement pstatementNode1;
        pstatementNode1 = (PStatement)nodeArrayList1.get(0);
	if(pstatementNode1 != null)
	{
	  listNode2.add(pstatementNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new60() /* reduce ANonTerminal$Statement */
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PStatement pstatementNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pstatementNode2 = (PStatement)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pstatementNode2 != null)
	{
	  listNode3.add(pstatementNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {3, SHIFT, 1}, {4, SHIFT, 2}, },
			{{-1, ERROR, 1}, {31, SHIFT, 5}, },
			{{-1, ERROR, 2}, {3, SHIFT, 6}, },
			{{-1, ERROR, 3}, {36, ACCEPT, -1}, },
			{{-1, REDUCE, 0}, },
			{{-1, ERROR, 5}, {24, SHIFT, 7}, },
			{{-1, ERROR, 6}, {31, SHIFT, 8}, },
			{{-1, ERROR, 7}, {4, SHIFT, 9}, {5, SHIFT, 10}, {6, SHIFT, 11}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, {25, SHIFT, 15}, },
			{{-1, ERROR, 8}, {24, SHIFT, 21}, },
			{{-1, ERROR, 9}, {5, SHIFT, 22}, {6, SHIFT, 23}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, },
			{{-1, ERROR, 10}, {6, SHIFT, 25}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, },
			{{-1, ERROR, 11}, {31, SHIFT, 27}, },
			{{-1, REDUCE, 23}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 1}, },
			{{-1, REDUCE, 55}, },
			{{-1, REDUCE, 5}, },
			{{-1, ERROR, 18}, {31, SHIFT, 28}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 20}, {4, SHIFT, 9}, {5, SHIFT, 10}, {6, SHIFT, 11}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, {25, SHIFT, 29}, },
			{{-1, ERROR, 21}, {4, SHIFT, 9}, {5, SHIFT, 10}, {6, SHIFT, 11}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, {25, SHIFT, 31}, },
			{{-1, ERROR, 22}, {6, SHIFT, 33}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, },
			{{-1, ERROR, 23}, {31, SHIFT, 35}, },
			{{-1, ERROR, 24}, {31, SHIFT, 36}, },
			{{-1, ERROR, 25}, {31, SHIFT, 37}, },
			{{-1, ERROR, 26}, {31, SHIFT, 38}, },
			{{-1, ERROR, 27}, {22, SHIFT, 39}, },
			{{-1, ERROR, 28}, {16, SHIFT, 40}, {22, SHIFT, 41}, {28, SHIFT, 42}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 56}, },
			{{-1, REDUCE, 2}, },
			{{-1, ERROR, 32}, {4, SHIFT, 9}, {5, SHIFT, 10}, {6, SHIFT, 11}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, {25, SHIFT, 44}, },
			{{-1, ERROR, 33}, {31, SHIFT, 45}, },
			{{-1, ERROR, 34}, {31, SHIFT, 46}, },
			{{-1, ERROR, 35}, {22, SHIFT, 47}, },
			{{-1, ERROR, 36}, {22, SHIFT, 48}, },
			{{-1, ERROR, 37}, {22, SHIFT, 49}, },
			{{-1, ERROR, 38}, {22, SHIFT, 50}, },
			{{-1, ERROR, 39}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, {23, SHIFT, 51}, },
			{{-1, ERROR, 40}, {22, SHIFT, 54}, {31, SHIFT, 55}, {32, SHIFT, 56}, {33, SHIFT, 57}, },
			{{-1, ERROR, 41}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, {23, SHIFT, 61}, },
			{{-1, REDUCE, 41}, },
			{{-1, ERROR, 43}, {28, SHIFT, 63}, },
			{{-1, REDUCE, 4}, },
			{{-1, ERROR, 45}, {22, SHIFT, 64}, },
			{{-1, ERROR, 46}, {22, SHIFT, 65}, },
			{{-1, ERROR, 47}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, {23, SHIFT, 66}, },
			{{-1, ERROR, 48}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, {23, SHIFT, 68}, },
			{{-1, ERROR, 49}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, {23, SHIFT, 70}, },
			{{-1, ERROR, 50}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, {23, SHIFT, 72}, },
			{{-1, ERROR, 51}, {24, SHIFT, 74}, },
			{{-1, ERROR, 52}, {31, SHIFT, 76}, },
			{{-1, ERROR, 53}, {23, SHIFT, 77}, },
			{{-1, ERROR, 54}, {22, SHIFT, 54}, {31, SHIFT, 55}, {32, SHIFT, 56}, {33, SHIFT, 57}, },
			{{-1, REDUCE, 51}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 53}, },
			{{-1, REDUCE, 43}, {18, SHIFT, 79}, {19, SHIFT, 80}, },
			{{-1, REDUCE, 47}, {20, SHIFT, 81}, {21, SHIFT, 82}, },
			{{-1, REDUCE, 50}, },
			{{-1, ERROR, 61}, {24, SHIFT, 74}, },
			{{-1, ERROR, 62}, {23, SHIFT, 84}, },
			{{-1, REDUCE, 42}, },
			{{-1, ERROR, 64}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, {23, SHIFT, 85}, },
			{{-1, ERROR, 65}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, {23, SHIFT, 87}, },
			{{-1, ERROR, 66}, {24, SHIFT, 74}, },
			{{-1, ERROR, 67}, {23, SHIFT, 90}, },
			{{-1, ERROR, 68}, {24, SHIFT, 74}, },
			{{-1, ERROR, 69}, {23, SHIFT, 92}, },
			{{-1, ERROR, 70}, {24, SHIFT, 74}, },
			{{-1, ERROR, 71}, {23, SHIFT, 94}, },
			{{-1, ERROR, 72}, {24, SHIFT, 74}, },
			{{-1, ERROR, 73}, {23, SHIFT, 96}, },
			{{-1, ERROR, 74}, {7, SHIFT, 97}, {8, SHIFT, 98}, {9, SHIFT, 99}, {10, SHIFT, 100}, {12, SHIFT, 101}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, {25, SHIFT, 102}, {31, SHIFT, 103}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 26}, {30, SHIFT, 109}, },
			{{-1, ERROR, 77}, {24, SHIFT, 74}, },
			{{-1, ERROR, 78}, {18, SHIFT, 79}, {19, SHIFT, 80}, {23, SHIFT, 113}, },
			{{-1, ERROR, 79}, {22, SHIFT, 54}, {31, SHIFT, 55}, {32, SHIFT, 56}, {33, SHIFT, 57}, },
			{{-1, ERROR, 80}, {22, SHIFT, 54}, {31, SHIFT, 55}, {32, SHIFT, 56}, {33, SHIFT, 57}, },
			{{-1, ERROR, 81}, {22, SHIFT, 54}, {31, SHIFT, 55}, {32, SHIFT, 56}, {33, SHIFT, 57}, },
			{{-1, ERROR, 82}, {22, SHIFT, 54}, {31, SHIFT, 55}, {32, SHIFT, 56}, {33, SHIFT, 57}, },
			{{-1, REDUCE, 8}, },
			{{-1, ERROR, 84}, {24, SHIFT, 74}, },
			{{-1, ERROR, 85}, {24, SHIFT, 74}, },
			{{-1, ERROR, 86}, {23, SHIFT, 120}, },
			{{-1, ERROR, 87}, {24, SHIFT, 74}, },
			{{-1, ERROR, 88}, {23, SHIFT, 122}, },
			{{-1, REDUCE, 9}, },
			{{-1, ERROR, 90}, {24, SHIFT, 74}, },
			{{-1, REDUCE, 10}, },
			{{-1, ERROR, 92}, {24, SHIFT, 74}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 94}, {24, SHIFT, 74}, },
			{{-1, REDUCE, 12}, },
			{{-1, ERROR, 96}, {24, SHIFT, 74}, },
			{{-1, ERROR, 97}, {22, SHIFT, 127}, },
			{{-1, ERROR, 98}, {24, SHIFT, 74}, },
			{{-1, ERROR, 99}, {22, SHIFT, 129}, },
			{{-1, ERROR, 100}, {22, SHIFT, 130}, },
			{{-1, ERROR, 101}, {22, SHIFT, 131}, },
			{{-1, REDUCE, 29}, },
			{{-1, ERROR, 103}, {16, SHIFT, 132}, },
			{{-1, ERROR, 104}, {31, SHIFT, 133}, },
			{{-1, REDUCE, 59}, },
			{{-1, ERROR, 106}, {28, SHIFT, 134}, },
			{{-1, REDUCE, 32}, },
			{{-1, ERROR, 108}, {7, SHIFT, 97}, {8, SHIFT, 98}, {9, SHIFT, 99}, {10, SHIFT, 100}, {12, SHIFT, 101}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, {25, SHIFT, 135}, {31, SHIFT, 103}, },
			{{-1, ERROR, 109}, {13, SHIFT, 12}, {14, SHIFT, 13}, {15, SHIFT, 14}, },
			{{-1, REDUCE, 57}, },
			{{-1, REDUCE, 27}, {30, SHIFT, 109}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 54}, },
			{{-1, REDUCE, 45}, {20, SHIFT, 81}, {21, SHIFT, 82}, },
			{{-1, REDUCE, 46}, {20, SHIFT, 81}, {21, SHIFT, 82}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 49}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 13}, },
			{{-1, ERROR, 120}, {24, SHIFT, 74}, },
			{{-1, REDUCE, 14}, },
			{{-1, ERROR, 122}, {24, SHIFT, 74}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 20}, },
			{{-1, ERROR, 127}, {31, SHIFT, 103}, },
			{{-1, ERROR, 128}, {9, SHIFT, 142}, },
			{{-1, ERROR, 129}, {22, SHIFT, 54}, {31, SHIFT, 55}, {32, SHIFT, 56}, {33, SHIFT, 57}, },
			{{-1, ERROR, 130}, {22, SHIFT, 54}, {31, SHIFT, 55}, {32, SHIFT, 56}, {33, SHIFT, 57}, },
			{{-1, ERROR, 131}, {22, SHIFT, 54}, {31, SHIFT, 55}, {32, SHIFT, 56}, {33, SHIFT, 57}, },
			{{-1, ERROR, 132}, {22, SHIFT, 54}, {31, SHIFT, 55}, {32, SHIFT, 56}, {33, SHIFT, 57}, },
			{{-1, ERROR, 133}, {16, SHIFT, 40}, {28, SHIFT, 42}, },
			{{-1, REDUCE, 31}, },
			{{-1, REDUCE, 30}, },
			{{-1, REDUCE, 60}, },
			{{-1, ERROR, 137}, {31, SHIFT, 148}, },
			{{-1, REDUCE, 58}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 22}, },
			{{-1, ERROR, 141}, {28, SHIFT, 149}, },
			{{-1, ERROR, 142}, {22, SHIFT, 150}, },
			{{-1, ERROR, 143}, {23, SHIFT, 151}, },
			{{-1, ERROR, 144}, {17, SHIFT, 152}, {18, SHIFT, 79}, {19, SHIFT, 80}, },
			{{-1, ERROR, 145}, {23, SHIFT, 153}, },
			{{-1, ERROR, 146}, {18, SHIFT, 79}, {19, SHIFT, 80}, {23, SHIFT, 154}, },
			{{-1, REDUCE, 39}, {18, SHIFT, 79}, {19, SHIFT, 80}, },
			{{-1, REDUCE, 28}, },
			{{-1, ERROR, 149}, {22, SHIFT, 54}, {31, SHIFT, 55}, {32, SHIFT, 56}, {33, SHIFT, 57}, },
			{{-1, ERROR, 150}, {22, SHIFT, 54}, {31, SHIFT, 55}, {32, SHIFT, 56}, {33, SHIFT, 57}, },
			{{-1, ERROR, 151}, {24, SHIFT, 74}, },
			{{-1, ERROR, 152}, {22, SHIFT, 54}, {31, SHIFT, 55}, {32, SHIFT, 56}, {33, SHIFT, 57}, },
			{{-1, ERROR, 153}, {24, SHIFT, 74}, },
			{{-1, ERROR, 154}, {28, SHIFT, 160}, },
			{{-1, ERROR, 155}, {28, SHIFT, 161}, },
			{{-1, ERROR, 156}, {23, SHIFT, 162}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 44}, {18, SHIFT, 79}, {19, SHIFT, 80}, },
			{{-1, REDUCE, 33}, {11, SHIFT, 163}, },
			{{-1, REDUCE, 38}, },
			{{-1, ERROR, 161}, {31, SHIFT, 103}, },
			{{-1, ERROR, 162}, {28, SHIFT, 166}, },
			{{-1, ERROR, 163}, {24, SHIFT, 74}, },
			{{-1, REDUCE, 34}, },
			{{-1, ERROR, 165}, {23, SHIFT, 168}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 40}, },
			{{-1, ERROR, 168}, {24, SHIFT, 74}, },
			{{-1, REDUCE, 37}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 3}, },
			{{-1, 4}, },
			{{-1, 16}, {20, 30}, {32, 30}, },
			{{-1, 17}, },
			{{-1, 52}, {7, 18}, {9, 24}, {10, 26}, {20, 18}, {21, 18}, {22, 34}, {32, 18}, {74, 104}, {108, 104}, {109, 137}, },
			{{-1, 53}, {41, 62}, {47, 67}, {48, 69}, {49, 71}, {50, 73}, {64, 86}, {65, 88}, },
			{{-1, 110}, {111, 138}, },
			{{-1, 75}, {61, 83}, {66, 89}, {68, 91}, {70, 93}, {72, 95}, {77, 112}, {84, 118}, {85, 119}, {87, 121}, {90, 123}, {92, 124}, {94, 125}, {96, 126}, {98, 128}, {120, 139}, {122, 140}, {151, 157}, {153, 159}, {163, 167}, {168, 169}, },
			{{-1, 105}, {108, 136}, },
			{{-1, 106}, {127, 141}, {161, 165}, },
			{{-1, 164}, },
			{{-1, 19}, {74, 107}, {108, 107}, },
			{{-1, 43}, },
			{{-1, 143}, {130, 145}, {149, 155}, {150, 156}, },
			{{-1, 144}, {40, 58}, {54, 78}, {131, 146}, {132, 147}, {152, 158}, },
			{{-1, 59}, {79, 114}, {80, 115}, },
			{{-1, 60}, {81, 116}, {82, 117}, },
			{{-1, 20}, {21, 32}, },
			{{-1, 111}, },
			{{-1, 108}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: clas, public",
			"expecting: ident",
			"expecting: clas",
			"expecting: EOF",
			"expecting: '{'",
			"expecting: public, static, void, int, float, string, '}'",
			"expecting: static, void, int, float, string",
			"expecting: void, int, float, string",
			"expecting: '('",
			"expecting: '=', '(', ';'",
			"expecting: int, float, string, ')'",
			"expecting: '(', ident, int literal, float literal",
			"expecting: public, static, void, for, do, while, if, main, int, float, string, '}', ident",
			"expecting: ';'",
			"expecting: ')'",
			"expecting: compare, '+', '-', '*', '/', ')', ';'",
			"expecting: '+', '-', ';'",
			"expecting: for, do, while, if, main, int, float, string, '}', ident",
			"expecting: ')', ','",
			"expecting: '+', '-', ')'",
			"expecting: public, static, void, for, do, while, if, else, main, int, float, string, '}', ident",
			"expecting: '='",
			"expecting: int, float, string",
			"expecting: while",
			"expecting: '=', ';'",
			"expecting: compare, '+', '-'",
			"expecting: '+', '-', ')', ';'",
			"expecting: for, do, while, if, else, main, int, float, string, '}', ident",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 3, 4, 1, 5, 4, 6, 7, 1, 1, 1, 1, 3, 5, 5, 1, 5, 5, 5, 7, 1, 1, 1, 1, 8, 9, 3, 5, 3, 5, 1, 1, 8, 8, 8, 8, 10, 11, 10, 12, 13, 3, 8, 8, 10, 10, 10, 10, 4, 1, 14, 11, 15, 15, 15, 16, 15, 15, 4, 14, 12, 10, 10, 4, 14, 4, 14, 4, 14, 4, 14, 17, 5, 18, 4, 19, 11, 11, 11, 11, 5, 4, 4, 14, 4, 14, 5, 4, 5, 4, 5, 4, 5, 4, 8, 4, 8, 8, 8, 20, 21, 1, 17, 13, 17, 17, 22, 18, 18, 5, 15, 15, 15, 15, 15, 5, 5, 4, 5, 4, 5, 5, 5, 5, 1, 23, 11, 11, 11, 11, 24, 17, 20, 17, 1, 18, 5, 5, 13, 8, 14, 25, 14, 19, 26, 18, 11, 11, 4, 11, 4, 13, 13, 14, 17, 26, 27, 17, 1, 13, 4, 17, 14, 17, 17, 4, 17, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            actionTable = new int[length][][];
            for(int i = 0; i < actionTable.length; i++)
            {
                length = s.readInt();
                actionTable[i] = new int[length][3];
                for(int j = 0; j < actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
