/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.parser;

import bahasaManusia.node.*;
import bahasaManusia.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTComment1(TComment1 node)
    {
        index = 0;
    }

    public void caseTComment2(TComment2 node)
    {
        index = 1;
    }

    public void caseTSpace(TSpace node)
    {
        index = 2;
    }

    public void caseTClas(TClas node)
    {
        index = 3;
    }

    public void caseTPublic(TPublic node)
    {
        index = 4;
    }

    public void caseTStatic(TStatic node)
    {
        index = 5;
    }

    public void caseTVoid(TVoid node)
    {
        index = 6;
    }

    public void caseTFor(TFor node)
    {
        index = 7;
    }

    public void caseTDo(TDo node)
    {
        index = 8;
    }

    public void caseTWhile(TWhile node)
    {
        index = 9;
    }

    public void caseTIf(TIf node)
    {
        index = 10;
    }

    public void caseTElse(TElse node)
    {
        index = 11;
    }

    public void caseTMain(TMain node)
    {
        index = 12;
    }

    public void caseTInt(TInt node)
    {
        index = 13;
    }

    public void caseTFloat(TFloat node)
    {
        index = 14;
    }

    public void caseTString(TString node)
    {
        index = 15;
    }

    public void caseTAssign(TAssign node)
    {
        index = 16;
    }

    public void caseTCompare(TCompare node)
    {
        index = 17;
    }

    public void caseTPlus(TPlus node)
    {
        index = 18;
    }

    public void caseTMinus(TMinus node)
    {
        index = 19;
    }

    public void caseTMult(TMult node)
    {
        index = 20;
    }

    public void caseTDiv(TDiv node)
    {
        index = 21;
    }

    public void caseTLPar(TLPar node)
    {
        index = 22;
    }

    public void caseTRPar(TRPar node)
    {
        index = 23;
    }

    public void caseTLBrace(TLBrace node)
    {
        index = 24;
    }

    public void caseTRBrace(TRBrace node)
    {
        index = 25;
    }

    public void caseTLBracket(TLBracket node)
    {
        index = 26;
    }

    public void caseTRBracket(TRBracket node)
    {
        index = 27;
    }

    public void caseTSemi(TSemi node)
    {
        index = 28;
    }

    public void caseTColon(TColon node)
    {
        index = 29;
    }

    public void caseTComma(TComma node)
    {
        index = 30;
    }

    public void caseTIdent(TIdent node)
    {
        index = 31;
    }

    public void caseTIntLiteral(TIntLiteral node)
    {
        index = 32;
    }

    public void caseTFloatLiteral(TFloatLiteral node)
    {
        index = 33;
    }

    public void caseTBlank(TBlank node)
    {
        index = 34;
    }

    public void caseTUnknown(TUnknown node)
    {
        index = 35;
    }

    public void caseEOF(EOF node)
    {
        index = 36;
    }
}
