/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura_VOD.node;

import sakura_VOD.analysis.*;

public final class TBegin extends Token
{
    public TBegin()
    {
        super.setText("mula");
    }

    public TBegin(int line, int pos)
    {
        super.setText("mula");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TBegin(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBegin(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TBegin text.");
    }
}
