/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura_VOD.node;

import sakura_VOD.analysis.*;

public final class TMoshi extends Token
{
    public TMoshi()
    {
        super.setText("jika");
    }

    public TMoshi(int line, int pos)
    {
        super.setText("jika");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMoshi(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMoshi(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMoshi text.");
    }
}
