/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura_VOD.node;

import sakura_VOD.analysis.*;

public final class TShikashi extends Token
{
    public TShikashi()
    {
        super.setText("selain");
    }

    public TShikashi(int line, int pos)
    {
        super.setText("selain");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TShikashi(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTShikashi(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TShikashi text.");
    }
}
