/* This file was generated by SableCC (http://www.sablecc.org/). */

package Manusiaberbahasa.lexer;

import java.io.*;
import java.util.*;
import Manusiaberbahasa.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = new32(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            Token token = new33(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            Token token = new34(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            Token token = new35(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(String text, int line, int pos) { return new TComment1(text, line, pos); }
    Token new1(String text, int line, int pos) { return new TComment2(text, line, pos); }
    Token new2(String text, int line, int pos) { return new TSpace(text, line, pos); }
    Token new3(String text, int line, int pos) { return new TClas(text, line, pos); }
    Token new4(String text, int line, int pos) { return new TPublic(text, line, pos); }
    Token new5(String text, int line, int pos) { return new TStatic(text, line, pos); }
    Token new6(String text, int line, int pos) { return new TVoid(text, line, pos); }
    Token new7(String text, int line, int pos) { return new TFor(text, line, pos); }
    Token new8(String text, int line, int pos) { return new TDo(text, line, pos); }
    Token new9(String text, int line, int pos) { return new TWhile(text, line, pos); }
    Token new10(String text, int line, int pos) { return new TIf(text, line, pos); }
    Token new11(String text, int line, int pos) { return new TElse(text, line, pos); }
    Token new12(String text, int line, int pos) { return new TMain(text, line, pos); }
    Token new13(String text, int line, int pos) { return new TInt(text, line, pos); }
    Token new14(String text, int line, int pos) { return new TFloat(text, line, pos); }
    Token new15(String text, int line, int pos) { return new TString(text, line, pos); }
    Token new16(int line, int pos) { return new TAssign(line, pos); }
    Token new17(String text, int line, int pos) { return new TCompare(text, line, pos); }
    Token new18(int line, int pos) { return new TPlus(line, pos); }
    Token new19(int line, int pos) { return new TMinus(line, pos); }
    Token new20(int line, int pos) { return new TMult(line, pos); }
    Token new21(int line, int pos) { return new TDiv(line, pos); }
    Token new22(int line, int pos) { return new TLPar(line, pos); }
    Token new23(int line, int pos) { return new TRPar(line, pos); }
    Token new24(int line, int pos) { return new TLBrace(line, pos); }
    Token new25(int line, int pos) { return new TRBrace(line, pos); }
    Token new26(int line, int pos) { return new TLBracket(line, pos); }
    Token new27(int line, int pos) { return new TRBracket(line, pos); }
    Token new28(int line, int pos) { return new TSemi(line, pos); }
    Token new29(int line, int pos) { return new TColon(line, pos); }
    Token new30(int line, int pos) { return new TComma(line, pos); }
    Token new31(String text, int line, int pos) { return new TIdent(text, line, pos); }
    Token new32(String text, int line, int pos) { return new TIntLiteral(text, line, pos); }
    Token new33(String text, int line, int pos) { return new TFloatLiteral(text, line, pos); }
    Token new34(String text, int line, int pos) { return new TBlank(text, line, pos); }
    Token new35(String text, int line, int pos) { return new TUnknown(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{0, 8, 1}, {9, 9, 2}, {10, 10, 3}, {11, 12, 1}, {13, 13, 4}, {14, 31, 1}, {32, 32, 5}, {33, 33, 6}, {34, 35, 1}, {36, 36, 7}, {37, 39, 1}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {46, 46, 14}, {47, 47, 15}, {48, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {63, 64, 1}, {65, 82, 22}, {83, 83, 23}, {84, 90, 22}, {91, 91, 24}, {92, 92, 25}, {93, 93, 26}, {94, 94, 1}, {95, 95, 27}, {96, 96, 1}, {97, 97, 28}, {98, 98, 29}, {99, 99, 30}, {100, 100, 31}, {101, 101, 32}, {102, 102, 33}, {103, 103, 34}, {104, 104, 35}, {105, 105, 36}, {106, 106, 37}, {107, 107, 38}, {108, 108, 39}, {109, 109, 40}, {110, 110, 41}, {111, 111, 42}, {112, 112, 43}, {113, 114, 42}, {115, 115, 44}, {116, 116, 45}, {117, 117, 46}, {118, 118, 47}, {119, 119, 48}, {120, 120, 42}, {121, 121, 49}, {122, 122, 42}, {123, 123, 50}, {124, 124, 1}, {125, 125, 51}, {126, 65535, 1}, },
            {},
            {},
            {{10, 10, 52}, {32, 32, 53}, {92, 92, 54}, },
            {},
            {{10, 92, -5}, },
            {{61, 61, 55}, },
            {{36, 36, 56}, {48, 57, 57}, {65, 90, 58}, {95, 95, 59}, {97, 122, 60}, },
            {},
            {},
            {},
            {},
            {},
            {{46, 46, 61}, {48, 57, 62}, },
            {{48, 57, 63}, },
            {{42, 42, 64}, {47, 47, 65}, },
            {{46, 46, 66}, {48, 57, 62}, },
            {},
            {},
            {{61, 61, 67}, },
            {{61, 61, 68}, },
            {{61, 61, 69}, },
            {{36, 122, -9}, },
            {{36, 95, -9}, {97, 115, 60}, {116, 116, 70}, {117, 122, 60}, },
            {},
            {{110, 110, 71}, {116, 116, 72}, },
            {},
            {{36, 122, -9}, },
            {{36, 95, -9}, {97, 104, 60}, {105, 105, 73}, {106, 108, 60}, {109, 109, 74}, {110, 110, 75}, {111, 111, 60}, {112, 112, 76}, {113, 118, 60}, {119, 119, 77}, {120, 120, 60}, {121, 121, 78}, {122, 122, 60}, },
            {{36, 95, -9}, {97, 116, 60}, {117, 117, 79}, {118, 122, 60}, },
            {{36, 95, -9}, {97, 107, 60}, {108, 108, 80}, {109, 122, 60}, },
            {{36, 95, -9}, {97, 97, 81}, {98, 110, 60}, {111, 111, 82}, {112, 122, 60}, },
            {{36, 107, -32}, {108, 108, 83}, {109, 122, 60}, },
            {{36, 107, -32}, {108, 108, 84}, {109, 110, 60}, {111, 111, 85}, {112, 116, 60}, {117, 117, 86}, {118, 122, 60}, },
            {{36, 95, -9}, {97, 100, 60}, {101, 101, 87}, {102, 122, 60}, },
            {{36, 95, -9}, {97, 110, 60}, {111, 111, 88}, {112, 122, 60}, },
            {{36, 95, -9}, {97, 101, 60}, {102, 102, 89}, {103, 109, 60}, {110, 110, 90}, {111, 122, 60}, },
            {{36, 104, -30}, {105, 105, 91}, {106, 122, 60}, },
            {{36, 95, -9}, {97, 97, 92}, {98, 107, 60}, {108, 108, 93}, {109, 110, 60}, {111, 111, 94}, {112, 116, 60}, {117, 117, 95}, {118, 122, 60}, },
            {{36, 95, -9}, {97, 97, 96}, {98, 104, 60}, {105, 105, 97}, {106, 122, 60}, },
            {{36, 95, -9}, {97, 97, 98}, {98, 100, 60}, {101, 101, 99}, {102, 110, 60}, {111, 111, 100}, {112, 116, 60}, {117, 117, 101}, {118, 122, 60}, },
            {{36, 95, -9}, {97, 97, 102}, {98, 110, 60}, {111, 111, 103}, {112, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 100, -36}, {101, 101, 104}, {102, 116, 60}, {117, 117, 105}, {118, 122, 60}, },
            {{36, 100, -36}, {101, 101, 106}, {102, 115, 60}, {116, 116, 107}, {117, 122, 60}, },
            {{36, 100, -36}, {101, 101, 108}, {102, 116, 60}, {117, 117, 109}, {118, 122, 60}, },
            {{36, 95, -9}, {97, 108, 60}, {109, 109, 110}, {110, 110, 111}, {111, 115, 60}, {116, 116, 112}, {117, 122, 60}, },
            {{36, 110, -37}, {111, 111, 113}, {112, 122, 60}, },
            {{36, 95, -9}, {97, 103, 60}, {104, 104, 114}, {105, 122, 60}, },
            {{36, 100, -36}, {101, 101, 115}, {102, 122, 60}, },
            {},
            {},
            {{10, 92, -5}, },
            {{10, 92, -5}, },
            {{110, 116, -27}, },
            {},
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{48, 57, 63}, },
            {{46, 57, -18}, },
            {{48, 57, 63}, {69, 69, 116}, {70, 70, 117}, {101, 101, 116}, {102, 102, 118}, },
            {{0, 41, 119}, {42, 42, 120}, {43, 65535, 119}, },
            {{0, 9, 121}, {10, 10, 122}, {11, 12, 121}, {13, 13, 122}, {14, 65535, 121}, },
            {{48, 57, 123}, {69, 102, -65}, },
            {},
            {},
            {},
            {{36, 95, -9}, {97, 113, 60}, {114, 114, 124}, {115, 122, 60}, },
            {{10, 92, -5}, },
            {{10, 92, -5}, },
            {{36, 95, -9}, {97, 99, 60}, {100, 100, 125}, {101, 122, 60}, },
            {{36, 95, -9}, {97, 97, 60}, {98, 98, 126}, {99, 122, 60}, },
            {{36, 95, -9}, {97, 102, 60}, {103, 103, 127}, {104, 122, 60}, },
            {{36, 95, -9}, {97, 97, 128}, {98, 122, 60}, },
            {{36, 95, -9}, {97, 97, 129}, {98, 122, 60}, },
            {{36, 95, -9}, {97, 97, 130}, {98, 122, 60}, },
            {{36, 95, -9}, {97, 97, 131}, {98, 122, 60}, },
            {{36, 95, -9}, {97, 97, 132}, {98, 122, 60}, },
            {{36, 113, -72}, {114, 114, 133}, {115, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 95, -9}, {97, 114, 60}, {115, 115, 134}, {116, 122, 60}, },
            {{36, 110, -37}, {111, 111, 135}, {112, 122, 60}, },
            {{36, 113, -72}, {114, 114, 136}, {115, 122, 60}, },
            {{36, 99, -75}, {100, 100, 137}, {101, 122, 60}, },
            {{36, 107, -32}, {108, 108, 138}, {109, 122, 60}, },
            {{36, 95, -9}, {97, 106, 60}, {107, 107, 139}, {108, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 115, -25}, {116, 116, 140}, {117, 122, 60}, },
            {{36, 106, -90}, {107, 107, 141}, {108, 122, 60}, },
            {{36, 95, -9}, {97, 109, 60}, {110, 110, 142}, {111, 122, 60}, },
            {{36, 95, -9}, {97, 97, 143}, {98, 122, 60}, },
            {{36, 114, -85}, {115, 115, 144}, {116, 116, 60}, {117, 117, 145}, {118, 122, 60}, },
            {{36, 113, -72}, {114, 114, 146}, {115, 122, 60}, },
            {{36, 106, -90}, {107, 107, 147}, {108, 122, 60}, },
            {{36, 95, -9}, {97, 120, 60}, {121, 121, 148}, {122, 122, 60}, },
            {{36, 104, -30}, {105, 105, 149}, {106, 122, 60}, },
            {{36, 104, -30}, {105, 105, 150}, {106, 122, 60}, },
            {{36, 95, -9}, {97, 105, 60}, {106, 106, 151}, {107, 114, 60}, {115, 115, 152}, {116, 122, 60}, },
            {{36, 106, -90}, {107, 107, 153}, {108, 122, 60}, },
            {{36, 107, -32}, {108, 108, 154}, {109, 122, 60}, },
            {{36, 108, -48}, {109, 109, 155}, {110, 122, 60}, },
            {{36, 102, -77}, {103, 103, 156}, {104, 113, 60}, {114, 114, 157}, {115, 122, 60}, },
            {{36, 97, -76}, {98, 98, 158}, {99, 122, 60}, },
            {{36, 104, -30}, {105, 105, 159}, {106, 107, 60}, {108, 108, 160}, {109, 122, 60}, },
            {{36, 95, -9}, {97, 97, 161}, {98, 122, 60}, },
            {{36, 115, -25}, {116, 116, 162}, {117, 122, 60}, },
            {{36, 107, -32}, {108, 108, 163}, {109, 122, 60}, },
            {{36, 116, -31}, {117, 117, 164}, {118, 122, 60}, },
            {{36, 115, -25}, {116, 116, 165}, {117, 122, 60}, },
            {{36, 95, -9}, {97, 97, 166}, {98, 122, 60}, },
            {{36, 104, -30}, {105, 105, 167}, {106, 122, 60}, },
            {{36, 104, -30}, {105, 105, 168}, {106, 122, 60}, },
            {{36, 109, -94}, {110, 110, 169}, {111, 122, 60}, },
            {{43, 43, 170}, {45, 45, 170}, {48, 57, 171}, },
            {},
            {},
            {{0, 65535, -66}, },
            {{0, 41, 172}, {43, 46, 172}, {47, 47, 173}, {48, 65535, 172}, },
            {{0, 65535, -67}, },
            {},
            {{48, 102, -68}, },
            {{36, 104, -30}, {105, 105, 174}, {106, 122, 60}, },
            {{36, 95, -9}, {97, 97, 175}, {98, 122, 60}, },
            {{36, 95, -9}, {97, 97, 176}, {98, 122, 60}, },
            {{36, 106, -90}, {107, 107, 177}, {108, 122, 60}, },
            {{36, 97, -76}, {98, 98, 178}, {99, 122, 60}, },
            {{36, 108, -48}, {109, 109, 179}, {110, 122, 60}, },
            {{36, 115, -25}, {116, 116, 180}, {117, 122, 60}, },
            {{36, 115, -25}, {116, 116, 181}, {117, 122, 60}, },
            {{36, 114, -85}, {115, 115, 182}, {116, 122, 60}, },
            {{36, 105, -102}, {106, 106, 183}, {107, 122, 60}, },
            {{36, 100, -36}, {101, 101, 184}, {102, 122, 60}, },
            {{36, 95, -9}, {97, 97, 185}, {98, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 110, -37}, {111, 111, 186}, {112, 122, 60}, },
            {{36, 95, -9}, {97, 97, 187}, {98, 122, 60}, },
            {{36, 95, -9}, {97, 97, 188}, {98, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 95, -9}, {97, 97, 189}, {98, 106, 60}, {107, 107, 190}, {108, 122, 60}, },
            {{36, 102, -77}, {103, 103, 191}, {104, 122, 60}, },
            {{36, 114, -85}, {115, 115, 192}, {116, 122, 60}, },
            {{36, 110, -37}, {111, 111, 193}, {112, 122, 60}, },
            {{36, 106, -90}, {107, 107, 194}, {108, 122, 60}, },
            {{36, 95, -9}, {97, 97, 195}, {98, 104, 60}, {105, 105, 196}, {106, 122, 60}, },
            {{36, 110, -37}, {111, 111, 197}, {112, 122, 60}, },
            {{36, 95, -9}, {97, 97, 198}, {98, 122, 60}, },
            {{36, 109, -94}, {110, 110, 199}, {111, 122, 60}, },
            {{36, 109, -94}, {110, 110, 200}, {111, 122, 60}, },
            {{36, 104, -30}, {105, 105, 201}, {106, 122, 60}, },
            {{36, 103, -50}, {104, 104, 202}, {105, 122, 60}, },
            {{36, 110, -37}, {111, 111, 203}, {112, 122, 60}, },
            {{36, 104, -30}, {105, 105, 204}, {106, 122, 60}, },
            {{36, 97, -76}, {98, 98, 205}, {99, 122, 60}, },
            {{36, 116, -31}, {117, 117, 206}, {118, 122, 60}, },
            {{36, 95, -9}, {97, 111, 60}, {112, 112, 207}, {113, 122, 60}, },
            {{36, 107, -32}, {108, 108, 208}, {109, 122, 60}, },
            {{36, 114, -85}, {115, 115, 209}, {116, 116, 210}, {117, 122, 60}, },
            {{36, 95, -9}, {97, 97, 211}, {98, 122, 60}, },
            {{36, 115, -25}, {116, 116, 212}, {117, 122, 60}, },
            {{36, 100, -36}, {101, 101, 213}, {102, 122, 60}, },
            {{36, 104, -30}, {105, 105, 214}, {106, 122, 60}, },
            {{36, 108, -48}, {109, 109, 215}, {110, 122, 60}, },
            {{36, 116, -31}, {117, 117, 216}, {118, 122, 60}, },
            {{36, 108, -48}, {109, 109, 217}, {110, 122, 60}, },
            {{36, 99, -75}, {100, 100, 218}, {101, 122, 60}, },
            {{36, 107, -32}, {108, 108, 219}, {109, 122, 60}, },
            {{36, 122, -9}, },
            {{48, 57, 171}, },
            {{48, 57, 171}, {70, 70, 117}, {102, 102, 118}, },
            {{0, 41, 220}, {42, 42, 221}, {43, 65535, 220}, },
            {},
            {{36, 109, -94}, {110, 110, 222}, {111, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 109, -94}, {110, 110, 223}, {111, 122, 60}, },
            {{36, 95, -9}, {97, 97, 224}, {98, 122, 60}, },
            {{36, 104, -30}, {105, 105, 225}, {106, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 114, -85}, {115, 115, 226}, {116, 122, 60}, },
            {{36, 95, -9}, {97, 97, 227}, {98, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 115, -25}, {116, 116, 228}, {117, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 111, -159}, {112, 112, 229}, {113, 122, 60}, },
            {{36, 109, -94}, {110, 110, 230}, {111, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 110, -37}, {111, 111, 231}, {112, 122, 60}, },
            {{36, 102, -77}, {103, 103, 232}, {104, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 109, -94}, {110, 110, 233}, {111, 122, 60}, },
            {{36, 95, -9}, {97, 97, 234}, {98, 122, 60}, },
            {{36, 114, -85}, {115, 115, 235}, {116, 122, 60}, },
            {{36, 106, -90}, {107, 107, 236}, {108, 122, 60}, },
            {{36, 109, -94}, {110, 110, 237}, {111, 122, 60}, },
            {{36, 109, -94}, {110, 110, 238}, {111, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 113, -72}, {114, 114, 239}, {115, 122, 60}, },
            {{36, 104, -30}, {105, 105, 240}, {106, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 106, -90}, {107, 107, 241}, {108, 122, 60}, },
            {{36, 110, -37}, {111, 111, 242}, {112, 122, 60}, },
            {{36, 109, -94}, {110, 110, 243}, {111, 122, 60}, },
            {{36, 116, -31}, {117, 117, 244}, {118, 122, 60}, },
            {{36, 104, -30}, {105, 105, 245}, {106, 122, 60}, },
            {{36, 116, -31}, {117, 117, 246}, {118, 122, 60}, },
            {{36, 100, -36}, {101, 101, 247}, {102, 122, 60}, },
            {{36, 104, -30}, {105, 105, 248}, {106, 122, 60}, },
            {{36, 104, -30}, {105, 105, 249}, {106, 122, 60}, },
            {{36, 111, -159}, {112, 112, 250}, {113, 122, 60}, },
            {{36, 114, -85}, {115, 115, 251}, {116, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 106, -90}, {107, 107, 252}, {108, 122, 60}, },
            {{36, 95, -9}, {97, 97, 253}, {98, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 100, -36}, {101, 101, 254}, {102, 122, 60}, },
            {{0, 65535, -174}, },
            {{0, 65535, -122}, },
            {{36, 102, -77}, {103, 103, 255}, {104, 122, 60}, },
            {{36, 102, -77}, {103, 103, 256}, {104, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 107, -32}, {108, 108, 257}, {109, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 103, -50}, {104, 104, 258}, {105, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 104, -30}, {105, 105, 259}, {106, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 110, -37}, {111, 111, 260}, {112, 122, 60}, },
            {{36, 102, -77}, {103, 103, 261}, {104, 122, 60}, },
            {{36, 104, -30}, {105, 105, 262}, {106, 122, 60}, },
            {{36, 116, -31}, {117, 117, 263}, {118, 122, 60}, },
            {{36, 95, -9}, {97, 97, 264}, {98, 122, 60}, },
            {{36, 104, -30}, {105, 105, 265}, {106, 122, 60}, },
            {{36, 100, -36}, {101, 101, 266}, {102, 122, 60}, },
            {{36, 100, -36}, {101, 101, 267}, {102, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 95, -9}, {97, 97, 268}, {98, 122, 60}, },
            {{36, 113, -72}, {114, 114, 269}, {115, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 107, -32}, {108, 108, 270}, {109, 122, 60}, },
            {{36, 95, -9}, {97, 98, 60}, {99, 99, 271}, {100, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 106, -90}, {107, 107, 272}, {108, 122, 60}, },
            {{36, 109, -94}, {110, 110, 273}, {111, 122, 60}, },
            {{36, 98, -247}, {99, 99, 274}, {100, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 95, -9}, {97, 97, 275}, {98, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 95, -9}, {97, 97, 276}, {98, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 100, -36}, {101, 101, 277}, {102, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 115, -25}, {116, 116, 278}, {117, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 97, -76}, {98, 98, 279}, {99, 122, 60}, },
            {{36, 116, -31}, {117, 117, 280}, {118, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 104, -30}, {105, 105, 281}, {106, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 109, -94}, {110, 110, 282}, {111, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 114, -85}, {115, 115, 283}, {116, 122, 60}, },
            {{36, 114, -85}, {115, 115, 284}, {116, 122, 60}, },
            {{36, 116, -31}, {117, 117, 285}, {118, 122, 60}, },
            {{36, 103, -50}, {104, 104, 286}, {105, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
            {{36, 103, -50}, {104, 104, 287}, {105, 122, 60}, },
            {{36, 116, -31}, {117, 117, 288}, {118, 122, 60}, },
            {{36, 107, -32}, {108, 108, 289}, {109, 122, 60}, },
            {{36, 95, -9}, {97, 97, 290}, {98, 122, 60}, },
            {{36, 104, -30}, {105, 105, 291}, {106, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 95, -9}, {97, 97, 292}, {98, 122, 60}, },
            {{36, 109, -94}, {110, 110, 293}, {111, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 115, -25}, {116, 116, 294}, {117, 122, 60}, },
            {{36, 122, -9}, },
            {{36, 122, -9}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 35, 2, 2, 2, 2, 35, 31, 22, 23, 20, 18, 30, 19, 35, 21, 32, 29, 28, 17, 16, 17, 31, 31, 26, 35, 27, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 24, 25, 34, 34, -1, 17, 31, 31, 31, 31, 31, -1, 32, 33, -1, -1, 33, 17, 17, 17, 31, 34, 34, 31, 31, 31, 31, 31, 31, 31, 31, 31, 8, 31, 31, 31, 31, 31, 31, 10, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, -1, 33, 33, -1, -1, -1, 0, 33, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 7, 31, 31, 31, 13, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 10, -1, 33, -1, 1, 31, 9, 31, 31, 31, 4, 15, 8, 31, 31, 11, 31, 14, 31, 31, 10, 31, 31, 3, 31, 31, 31, 31, 31, 31, 12, 12, 31, 31, 6, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 4, 31, 31, 6, 31, -1, -1, 31, 31, 13, 31, 3, 31, 14, 6, 31, 8, 31, 31, 31, 31, 31, 31, 31, 31, 10, 31, 31, 5, 31, 31, 13, 31, 31, 31, 5, 31, 7, 12, 9, 15, 14, 31, 3, 11, 7, 6, 4, 3, 31, 8, 11, 31, 9, 31, 31, 4, 31, 11, 5, 31, 9, 31, 31, 31, 31, 5, 15, 31, 31, 31, 31, 31, 15, 31, 31, 7, 31, 14, 13, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
