/* This file was generated by SableCC (http://www.sablecc.org/). */

package bahasaManusia.lexer;

import java.io.*;
import java.util.*;
import bahasaManusia.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = new32(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            Token token = new33(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            Token token = new34(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            Token token = new35(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(String text, int line, int pos) { return new TComment1(text, line, pos); }
    Token new1(String text, int line, int pos) { return new TComment2(text, line, pos); }
    Token new2(String text, int line, int pos) { return new TSpace(text, line, pos); }
    Token new3(String text, int line, int pos) { return new TClas(text, line, pos); }
    Token new4(String text, int line, int pos) { return new TPublic(text, line, pos); }
    Token new5(String text, int line, int pos) { return new TStatic(text, line, pos); }
    Token new6(String text, int line, int pos) { return new TVoid(text, line, pos); }
    Token new7(String text, int line, int pos) { return new TFor(text, line, pos); }
    Token new8(String text, int line, int pos) { return new TDo(text, line, pos); }
    Token new9(String text, int line, int pos) { return new TWhile(text, line, pos); }
    Token new10(String text, int line, int pos) { return new TIf(text, line, pos); }
    Token new11(String text, int line, int pos) { return new TElse(text, line, pos); }
    Token new12(String text, int line, int pos) { return new TMain(text, line, pos); }
    Token new13(String text, int line, int pos) { return new TInt(text, line, pos); }
    Token new14(String text, int line, int pos) { return new TFloat(text, line, pos); }
    Token new15(String text, int line, int pos) { return new TString(text, line, pos); }
    Token new16(int line, int pos) { return new TAssign(line, pos); }
    Token new17(String text, int line, int pos) { return new TCompare(text, line, pos); }
    Token new18(int line, int pos) { return new TPlus(line, pos); }
    Token new19(int line, int pos) { return new TMinus(line, pos); }
    Token new20(int line, int pos) { return new TMult(line, pos); }
    Token new21(int line, int pos) { return new TDiv(line, pos); }
    Token new22(int line, int pos) { return new TLPar(line, pos); }
    Token new23(int line, int pos) { return new TRPar(line, pos); }
    Token new24(int line, int pos) { return new TLBrace(line, pos); }
    Token new25(int line, int pos) { return new TRBrace(line, pos); }
    Token new26(int line, int pos) { return new TLBracket(line, pos); }
    Token new27(int line, int pos) { return new TRBracket(line, pos); }
    Token new28(int line, int pos) { return new TSemi(line, pos); }
    Token new29(int line, int pos) { return new TColon(line, pos); }
    Token new30(int line, int pos) { return new TComma(line, pos); }
    Token new31(String text, int line, int pos) { return new TIdent(text, line, pos); }
    Token new32(String text, int line, int pos) { return new TIntLiteral(text, line, pos); }
    Token new33(String text, int line, int pos) { return new TFloatLiteral(text, line, pos); }
    Token new34(String text, int line, int pos) { return new TBlank(text, line, pos); }
    Token new35(String text, int line, int pos) { return new TUnknown(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{0, 8, 1}, {9, 9, 2}, {10, 10, 3}, {11, 12, 1}, {13, 13, 4}, {14, 31, 1}, {32, 32, 5}, {33, 33, 6}, {34, 35, 1}, {36, 36, 7}, {37, 39, 1}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {46, 46, 14}, {47, 47, 15}, {48, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {63, 64, 1}, {65, 82, 22}, {83, 83, 23}, {84, 90, 22}, {91, 91, 24}, {92, 92, 25}, {93, 93, 26}, {94, 94, 1}, {95, 95, 27}, {96, 96, 1}, {97, 97, 28}, {98, 98, 29}, {99, 99, 30}, {100, 100, 31}, {101, 101, 32}, {102, 102, 33}, {103, 103, 34}, {104, 104, 35}, {105, 105, 36}, {106, 106, 37}, {107, 107, 38}, {108, 108, 39}, {109, 109, 40}, {110, 110, 41}, {111, 111, 42}, {112, 112, 43}, {113, 114, 42}, {115, 115, 44}, {116, 116, 45}, {117, 117, 46}, {118, 118, 47}, {119, 119, 48}, {120, 120, 42}, {121, 121, 49}, {122, 122, 42}, {123, 123, 50}, {124, 124, 1}, {125, 125, 51}, {126, 12352, 1}, {12353, 12353, 52}, {12354, 12354, 53}, {12355, 12366, 52}, {12367, 12367, 54}, {12368, 12370, 52}, {12371, 12371, 55}, {12372, 12375, 52}, {12376, 12376, 56}, {12377, 12378, 52}, {12379, 12379, 57}, {12380, 12404, 52}, {12405, 12405, 58}, {12406, 12410, 52}, {12411, 12411, 59}, {12412, 12415, 52}, {12416, 12416, 60}, {12417, 12417, 61}, {12418, 12418, 62}, {12419, 12438, 52}, {12439, 65535, 1}, },
            {},
            {},
            {{10, 10, 63}, {32, 32, 64}, {92, 92, 65}, },
            {},
            {{10, 92, -5}, },
            {{61, 61, 66}, },
            {{36, 36, 67}, {48, 57, 68}, {65, 90, 69}, {95, 95, 70}, {97, 122, 71}, {12353, 12438, 72}, },
            {},
            {},
            {},
            {},
            {},
            {{46, 46, 73}, {48, 57, 74}, },
            {{48, 57, 75}, },
            {{42, 42, 76}, {47, 47, 77}, },
            {{46, 46, 78}, {48, 57, 74}, },
            {},
            {},
            {{61, 61, 79}, },
            {{61, 61, 80}, },
            {{61, 61, 81}, },
            {{36, 12438, -9}, },
            {{36, 95, -9}, {97, 115, 71}, {116, 116, 82}, {117, 122, 71}, {12353, 12438, 72}, },
            {},
            {{110, 110, 83}, {116, 116, 84}, },
            {},
            {{36, 12438, -9}, },
            {{36, 95, -9}, {97, 104, 71}, {105, 105, 85}, {106, 108, 71}, {109, 109, 86}, {110, 110, 87}, {111, 111, 71}, {112, 112, 88}, {113, 118, 71}, {119, 119, 89}, {120, 120, 71}, {121, 121, 90}, {122, 122, 71}, {12353, 12438, 72}, },
            {{36, 95, -9}, {97, 116, 71}, {117, 117, 91}, {118, 122, 71}, {12353, 12438, 72}, },
            {{36, 95, -9}, {97, 107, 71}, {108, 108, 92}, {109, 122, 71}, {12353, 12438, 72}, },
            {{36, 95, -9}, {97, 97, 93}, {98, 110, 71}, {111, 111, 94}, {112, 122, 71}, {12353, 12438, 72}, },
            {{36, 107, -32}, {108, 108, 95}, {109, 12438, -32}, },
            {{36, 107, -32}, {108, 108, 96}, {109, 110, 71}, {111, 111, 97}, {112, 116, 71}, {117, 117, 98}, {118, 12438, -31}, },
            {{36, 95, -9}, {97, 100, 71}, {101, 101, 99}, {102, 122, 71}, {12353, 12438, 72}, },
            {{36, 95, -9}, {97, 110, 71}, {111, 111, 100}, {112, 12438, -33}, },
            {{36, 95, -9}, {97, 101, 71}, {102, 102, 101}, {103, 109, 71}, {110, 110, 102}, {111, 122, 71}, {12353, 12438, 72}, },
            {{36, 104, -30}, {105, 105, 103}, {106, 122, 71}, {12353, 12438, 72}, },
            {{36, 95, -9}, {97, 97, 104}, {98, 107, 71}, {108, 108, 105}, {109, 110, 71}, {111, 111, 106}, {112, 116, 71}, {117, 117, 107}, {118, 12438, -31}, },
            {{36, 95, -9}, {97, 97, 108}, {98, 104, 71}, {105, 105, 109}, {106, 12438, -39}, },
            {{36, 95, -9}, {97, 97, 110}, {98, 100, 71}, {101, 101, 111}, {102, 110, 71}, {111, 111, 112}, {112, 116, 71}, {117, 117, 113}, {118, 12438, -31}, },
            {{36, 95, -9}, {97, 97, 114}, {98, 110, 71}, {111, 111, 115}, {112, 12438, -33}, },
            {{36, 12438, -9}, },
            {{36, 100, -36}, {101, 101, 116}, {102, 116, 71}, {117, 117, 117}, {118, 12438, -31}, },
            {{36, 100, -36}, {101, 101, 118}, {102, 115, 71}, {116, 116, 119}, {117, 12438, -25}, },
            {{36, 100, -36}, {101, 101, 120}, {102, 116, 71}, {117, 117, 121}, {118, 12438, -31}, },
            {{36, 95, -9}, {97, 108, 71}, {109, 109, 122}, {110, 110, 123}, {111, 115, 71}, {116, 116, 124}, {117, 12438, -25}, },
            {{36, 110, -37}, {111, 111, 125}, {112, 12438, -33}, },
            {{36, 95, -9}, {97, 103, 71}, {104, 104, 126}, {105, 122, 71}, {12353, 12438, 72}, },
            {{36, 100, -36}, {101, 101, 127}, {102, 12438, -36}, },
            {},
            {},
            {{36, 12438, -9}, },
            {{36, 122, -9}, {12353, 12355, 72}, {12356, 12356, 128}, {12357, 12438, 72}, },
            {{36, 122, -9}, {12353, 12424, 72}, {12425, 12425, 129}, {12426, 12426, 130}, {12427, 12438, 72}, },
            {{36, 122, -9}, {12353, 12357, 72}, {12358, 12358, 131}, {12359, 12438, 72}, },
            {{36, 122, -9}, {12353, 12386, 72}, {12387, 12387, 132}, {12388, 12438, 72}, },
            {{36, 12355, -55}, {12356, 12356, 133}, {12357, 12438, 72}, },
            {{36, 122, -9}, {12353, 12392, 72}, {12393, 12393, 134}, {12394, 12438, 72}, },
            {{36, 122, -9}, {12353, 12362, 72}, {12363, 12363, 135}, {12364, 12438, 72}, },
            {{36, 122, -9}, {12353, 12370, 72}, {12371, 12371, 136}, {12372, 12438, 72}, },
            {{36, 12355, -55}, {12356, 12356, 137}, {12357, 12438, 72}, },
            {{36, 122, -9}, {12353, 12374, 72}, {12375, 12375, 138}, {12376, 12376, 139}, {12377, 12438, 72}, },
            {{10, 92, -5}, },
            {{10, 92, -5}, },
            {{110, 116, -27}, },
            {},
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{48, 57, 75}, },
            {{46, 57, -18}, },
            {{48, 57, 75}, {69, 69, 140}, {70, 70, 141}, {101, 101, 140}, {102, 102, 142}, },
            {{0, 41, 143}, {42, 42, 144}, {43, 65535, 143}, },
            {{0, 9, 145}, {10, 10, 146}, {11, 12, 145}, {13, 13, 146}, {14, 65535, 145}, },
            {{48, 57, 147}, {69, 102, -77}, },
            {},
            {},
            {},
            {{36, 95, -9}, {97, 113, 71}, {114, 114, 148}, {115, 122, 71}, {12353, 12438, 72}, },
            {{10, 92, -5}, },
            {{10, 92, -5}, },
            {{36, 95, -9}, {97, 99, 71}, {100, 100, 149}, {101, 122, 71}, {12353, 12438, 72}, },
            {{36, 95, -9}, {97, 97, 71}, {98, 98, 150}, {99, 122, 71}, {12353, 12438, 72}, },
            {{36, 95, -9}, {97, 102, 71}, {103, 103, 151}, {104, 122, 71}, {12353, 12438, 72}, },
            {{36, 95, -9}, {97, 97, 152}, {98, 122, 71}, {12353, 12438, 72}, },
            {{36, 95, -9}, {97, 97, 153}, {98, 12438, -90}, },
            {{36, 95, -9}, {97, 97, 154}, {98, 12438, -90}, },
            {{36, 95, -9}, {97, 97, 155}, {98, 12438, -90}, },
            {{36, 95, -9}, {97, 97, 156}, {98, 12438, -90}, },
            {{36, 113, -84}, {114, 114, 157}, {115, 12438, -84}, },
            {{36, 12438, -9}, },
            {{36, 95, -9}, {97, 114, 71}, {115, 115, 158}, {116, 122, 71}, {12353, 12438, 72}, },
            {{36, 110, -37}, {111, 111, 159}, {112, 12438, -33}, },
            {{36, 113, -84}, {114, 114, 160}, {115, 12438, -84}, },
            {{36, 99, -87}, {100, 100, 161}, {101, 12438, -87}, },
            {{36, 107, -32}, {108, 108, 162}, {109, 12438, -32}, },
            {{36, 95, -9}, {97, 106, 71}, {107, 107, 163}, {108, 122, 71}, {12353, 12438, 72}, },
            {{36, 12438, -9}, },
            {{36, 115, -25}, {116, 116, 164}, {117, 12438, -25}, },
            {{36, 106, -102}, {107, 107, 165}, {108, 12438, -102}, },
            {{36, 95, -9}, {97, 109, 71}, {110, 110, 166}, {111, 12438, -38}, },
            {{36, 95, -9}, {97, 97, 167}, {98, 12438, -90}, },
            {{36, 114, -97}, {115, 115, 168}, {116, 116, 71}, {117, 117, 169}, {118, 12438, -31}, },
            {{36, 113, -84}, {114, 114, 170}, {115, 12438, -84}, },
            {{36, 106, -102}, {107, 107, 171}, {108, 12438, -102}, },
            {{36, 95, -9}, {97, 120, 71}, {121, 121, 172}, {122, 12438, -30}, },
            {{36, 104, -30}, {105, 105, 173}, {106, 12438, -39}, },
            {{36, 104, -30}, {105, 105, 174}, {106, 12438, -39}, },
            {{36, 95, -9}, {97, 105, 71}, {106, 106, 175}, {107, 114, 71}, {115, 115, 176}, {116, 12438, -97}, },
            {{36, 106, -102}, {107, 107, 177}, {108, 12438, -102}, },
            {{36, 107, -32}, {108, 108, 178}, {109, 12438, -32}, },
            {{36, 108, -48}, {109, 109, 179}, {110, 122, 71}, {12353, 12438, 72}, },
            {{36, 102, -89}, {103, 103, 180}, {104, 113, 71}, {114, 114, 181}, {115, 12438, -84}, },
            {{36, 97, -88}, {98, 98, 182}, {99, 12438, -88}, },
            {{36, 104, -30}, {105, 105, 183}, {106, 107, 71}, {108, 108, 184}, {109, 12438, -32}, },
            {{36, 95, -9}, {97, 97, 185}, {98, 12438, -90}, },
            {{36, 115, -25}, {116, 116, 186}, {117, 12438, -25}, },
            {{36, 107, -32}, {108, 108, 187}, {109, 12438, -32}, },
            {{36, 116, -31}, {117, 117, 188}, {118, 12438, -31}, },
            {{36, 115, -25}, {116, 116, 189}, {117, 12438, -25}, },
            {{36, 95, -9}, {97, 97, 190}, {98, 12438, -90}, },
            {{36, 104, -30}, {105, 105, 191}, {106, 12438, -39}, },
            {{36, 104, -30}, {105, 105, 192}, {106, 12438, -39}, },
            {{36, 109, -106}, {110, 110, 193}, {111, 12438, -38}, },
            {{36, 122, -9}, {12353, 12383, 72}, {12384, 12384, 194}, {12385, 12438, 72}, },
            {{36, 122, -9}, {12353, 12376, 72}, {12377, 12377, 195}, {12378, 12438, 72}, },
            {{36, 12362, -61}, {12363, 12363, 196}, {12364, 12438, 72}, },
            {{36, 12362, -61}, {12363, 12363, 197}, {12364, 12438, 72}, },
            {{36, 12370, -62}, {12371, 12371, 198}, {12372, 12438, 72}, },
            {{36, 12376, -131}, {12377, 12377, 199}, {12378, 12389, 72}, {12390, 12390, 200}, {12391, 12438, 72}, },
            {{36, 12357, -57}, {12358, 12358, 201}, {12359, 12438, 72}, },
            {{36, 122, -9}, {12353, 12394, 72}, {12395, 12395, 202}, {12396, 12438, 72}, },
            {{36, 12357, -57}, {12358, 12358, 203}, {12359, 12438, 72}, },
            {{36, 122, -9}, {12353, 12434, 72}, {12435, 12435, 204}, {12436, 12438, 72}, },
            {{36, 12438, -9}, },
            {{36, 122, -9}, {12353, 12427, 72}, {12428, 12428, 205}, {12429, 12438, 72}, },
            {{43, 43, 206}, {45, 45, 206}, {48, 57, 207}, },
            {},
            {},
            {{0, 65535, -78}, },
            {{0, 41, 208}, {43, 46, 208}, {47, 47, 209}, {48, 65535, 208}, },
            {{0, 65535, -79}, },
            {},
            {{48, 102, -80}, },
            {{36, 104, -30}, {105, 105, 210}, {106, 12438, -39}, },
            {{36, 95, -9}, {97, 97, 211}, {98, 12438, -90}, },
            {{36, 95, -9}, {97, 97, 212}, {98, 12438, -90}, },
            {{36, 106, -102}, {107, 107, 213}, {108, 12438, -102}, },
            {{36, 97, -88}, {98, 98, 214}, {99, 12438, -88}, },
            {{36, 108, -48}, {109, 109, 215}, {110, 12438, -117}, },
            {{36, 115, -25}, {116, 116, 216}, {117, 12438, -25}, },
            {{36, 115, -25}, {116, 116, 217}, {117, 12438, -25}, },
            {{36, 114, -97}, {115, 115, 218}, {116, 12438, -97}, },
            {{36, 105, -114}, {106, 106, 219}, {107, 122, 71}, {12353, 12438, 72}, },
            {{36, 100, -36}, {101, 101, 220}, {102, 12438, -36}, },
            {{36, 95, -9}, {97, 97, 221}, {98, 12438, -90}, },
            {{36, 12438, -9}, },
            {{36, 110, -37}, {111, 111, 222}, {112, 12438, -33}, },
            {{36, 95, -9}, {97, 97, 223}, {98, 12438, -90}, },
            {{36, 95, -9}, {97, 97, 224}, {98, 12438, -90}, },
            {{36, 12438, -9}, },
            {{36, 95, -9}, {97, 97, 225}, {98, 106, 71}, {107, 107, 226}, {108, 12438, -102}, },
            {{36, 102, -89}, {103, 103, 227}, {104, 12438, -89}, },
            {{36, 114, -97}, {115, 115, 228}, {116, 12438, -97}, },
            {{36, 110, -37}, {111, 111, 229}, {112, 12438, -33}, },
            {{36, 106, -102}, {107, 107, 230}, {108, 12438, -102}, },
            {{36, 95, -9}, {97, 97, 231}, {98, 104, 71}, {105, 105, 232}, {106, 12438, -39}, },
            {{36, 110, -37}, {111, 111, 233}, {112, 12438, -33}, },
            {{36, 95, -9}, {97, 97, 234}, {98, 12438, -90}, },
            {{36, 109, -106}, {110, 110, 235}, {111, 12438, -38}, },
            {{36, 109, -106}, {110, 110, 236}, {111, 12438, -38}, },
            {{36, 104, -30}, {105, 105, 237}, {106, 12438, -39}, },
            {{36, 103, -50}, {104, 104, 238}, {105, 12438, -50}, },
            {{36, 110, -37}, {111, 111, 239}, {112, 12438, -33}, },
            {{36, 104, -30}, {105, 105, 240}, {106, 12438, -39}, },
            {{36, 97, -88}, {98, 98, 241}, {99, 12438, -88}, },
            {{36, 116, -31}, {117, 117, 242}, {118, 12438, -31}, },
            {{36, 95, -9}, {97, 111, 71}, {112, 112, 243}, {113, 122, 71}, {12353, 12438, 72}, },
            {{36, 107, -32}, {108, 108, 244}, {109, 12438, -32}, },
            {{36, 114, -97}, {115, 115, 245}, {116, 116, 246}, {117, 12438, -25}, },
            {{36, 95, -9}, {97, 97, 247}, {98, 12438, -90}, },
            {{36, 115, -25}, {116, 116, 248}, {117, 12438, -25}, },
            {{36, 100, -36}, {101, 101, 249}, {102, 12438, -36}, },
            {{36, 104, -30}, {105, 105, 250}, {106, 12438, -39}, },
            {{36, 108, -48}, {109, 109, 251}, {110, 12438, -117}, },
            {{36, 116, -31}, {117, 117, 252}, {118, 12438, -31}, },
            {{36, 108, -48}, {109, 109, 253}, {110, 12438, -117}, },
            {{36, 99, -87}, {100, 100, 254}, {101, 12438, -87}, },
            {{36, 107, -32}, {108, 108, 255}, {109, 12438, -32}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 122, -9}, {12353, 12359, 72}, {12360, 12360, 256}, {12361, 12438, 72}, },
            {{36, 12355, -55}, {12356, 12356, 257}, {12357, 12438, 72}, },
            {{36, 12357, -57}, {12358, 12358, 258}, {12359, 12438, 72}, },
            {{36, 12357, -57}, {12358, 12358, 259}, {12359, 12438, 72}, },
            {{36, 122, -9}, {12353, 12364, 72}, {12365, 12365, 260}, {12366, 12438, 72}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 122, -9}, {12353, 12387, 72}, {12388, 12388, 261}, {12389, 12438, 72}, },
            {{48, 57, 207}, },
            {{48, 57, 207}, {70, 70, 141}, {102, 102, 142}, },
            {{0, 41, 262}, {42, 42, 263}, {43, 65535, 262}, },
            {},
            {{36, 109, -106}, {110, 110, 264}, {111, 12438, -38}, },
            {{36, 12438, -9}, },
            {{36, 109, -106}, {110, 110, 265}, {111, 12438, -38}, },
            {{36, 95, -9}, {97, 97, 266}, {98, 12438, -90}, },
            {{36, 104, -30}, {105, 105, 267}, {106, 12438, -39}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 114, -97}, {115, 115, 268}, {116, 12438, -97}, },
            {{36, 95, -9}, {97, 97, 269}, {98, 12438, -90}, },
            {{36, 12438, -9}, },
            {{36, 115, -25}, {116, 116, 270}, {117, 12438, -25}, },
            {{36, 12438, -9}, },
            {{36, 111, -183}, {112, 112, 271}, {113, 12438, -183}, },
            {{36, 109, -106}, {110, 110, 272}, {111, 12438, -38}, },
            {{36, 12438, -9}, },
            {{36, 110, -37}, {111, 111, 273}, {112, 12438, -33}, },
            {{36, 102, -89}, {103, 103, 274}, {104, 12438, -89}, },
            {{36, 12438, -9}, },
            {{36, 109, -106}, {110, 110, 275}, {111, 12438, -38}, },
            {{36, 95, -9}, {97, 97, 276}, {98, 12438, -90}, },
            {{36, 114, -97}, {115, 115, 277}, {116, 12438, -97}, },
            {{36, 106, -102}, {107, 107, 278}, {108, 12438, -102}, },
            {{36, 109, -106}, {110, 110, 279}, {111, 12438, -38}, },
            {{36, 109, -106}, {110, 110, 280}, {111, 12438, -38}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 113, -84}, {114, 114, 281}, {115, 12438, -84}, },
            {{36, 104, -30}, {105, 105, 282}, {106, 12438, -39}, },
            {{36, 12438, -9}, },
            {{36, 106, -102}, {107, 107, 283}, {108, 12438, -102}, },
            {{36, 110, -37}, {111, 111, 284}, {112, 12438, -33}, },
            {{36, 109, -106}, {110, 110, 285}, {111, 12438, -38}, },
            {{36, 116, -31}, {117, 117, 286}, {118, 12438, -31}, },
            {{36, 104, -30}, {105, 105, 287}, {106, 12438, -39}, },
            {{36, 116, -31}, {117, 117, 288}, {118, 12438, -31}, },
            {{36, 100, -36}, {101, 101, 289}, {102, 12438, -36}, },
            {{36, 104, -30}, {105, 105, 290}, {106, 12438, -39}, },
            {{36, 104, -30}, {105, 105, 291}, {106, 12438, -39}, },
            {{36, 111, -183}, {112, 112, 292}, {113, 12438, -183}, },
            {{36, 114, -97}, {115, 115, 293}, {116, 12438, -97}, },
            {{36, 12438, -9}, },
            {{36, 106, -102}, {107, 107, 294}, {108, 12438, -102}, },
            {{36, 95, -9}, {97, 97, 295}, {98, 12438, -90}, },
            {{36, 12438, -9}, },
            {{36, 100, -36}, {101, 101, 296}, {102, 12438, -36}, },
            {{36, 12374, -64}, {12375, 12375, 297}, {12376, 12438, 72}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{0, 65535, -210}, },
            {{0, 65535, -146}, },
            {{36, 102, -89}, {103, 103, 298}, {104, 12438, -89}, },
            {{36, 102, -89}, {103, 103, 299}, {104, 12438, -89}, },
            {{36, 12438, -9}, },
            {{36, 107, -32}, {108, 108, 300}, {109, 12438, -32}, },
            {{36, 12438, -9}, },
            {{36, 103, -50}, {104, 104, 301}, {105, 12438, -50}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 104, -30}, {105, 105, 302}, {106, 12438, -39}, },
            {{36, 12438, -9}, },
            {{36, 110, -37}, {111, 111, 303}, {112, 12438, -33}, },
            {{36, 102, -89}, {103, 103, 304}, {104, 12438, -89}, },
            {{36, 104, -30}, {105, 105, 305}, {106, 12438, -39}, },
            {{36, 116, -31}, {117, 117, 306}, {118, 12438, -31}, },
            {{36, 95, -9}, {97, 97, 307}, {98, 12438, -90}, },
            {{36, 104, -30}, {105, 105, 308}, {106, 12438, -39}, },
            {{36, 100, -36}, {101, 101, 309}, {102, 12438, -36}, },
            {{36, 100, -36}, {101, 101, 310}, {102, 12438, -36}, },
            {{36, 12438, -9}, },
            {{36, 95, -9}, {97, 97, 311}, {98, 12438, -90}, },
            {{36, 113, -84}, {114, 114, 312}, {115, 12438, -84}, },
            {{36, 12438, -9}, },
            {{36, 107, -32}, {108, 108, 313}, {109, 12438, -32}, },
            {{36, 95, -9}, {97, 98, 71}, {99, 99, 314}, {100, 122, 71}, {12353, 12438, 72}, },
            {{36, 12438, -9}, },
            {{36, 106, -102}, {107, 107, 315}, {108, 12438, -102}, },
            {{36, 109, -106}, {110, 110, 316}, {111, 12438, -38}, },
            {{36, 98, -289}, {99, 99, 317}, {100, 12438, -289}, },
            {{36, 12438, -9}, },
            {{36, 95, -9}, {97, 97, 318}, {98, 12438, -90}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 95, -9}, {97, 97, 319}, {98, 12438, -90}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 100, -36}, {101, 101, 320}, {102, 12438, -36}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 115, -25}, {116, 116, 321}, {117, 12438, -25}, },
            {{36, 12438, -9}, },
            {{36, 97, -88}, {98, 98, 322}, {99, 12438, -88}, },
            {{36, 116, -31}, {117, 117, 323}, {118, 12438, -31}, },
            {{36, 12438, -9}, },
            {{36, 104, -30}, {105, 105, 324}, {106, 12438, -39}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 109, -106}, {110, 110, 325}, {111, 12438, -38}, },
            {{36, 12438, -9}, },
            {{36, 114, -97}, {115, 115, 326}, {116, 12438, -97}, },
            {{36, 114, -97}, {115, 115, 327}, {116, 12438, -97}, },
            {{36, 116, -31}, {117, 117, 328}, {118, 12438, -31}, },
            {{36, 103, -50}, {104, 104, 329}, {105, 12438, -50}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
            {{36, 103, -50}, {104, 104, 330}, {105, 12438, -50}, },
            {{36, 116, -31}, {117, 117, 331}, {118, 12438, -31}, },
            {{36, 107, -32}, {108, 108, 332}, {109, 12438, -32}, },
            {{36, 95, -9}, {97, 97, 333}, {98, 12438, -90}, },
            {{36, 104, -30}, {105, 105, 334}, {106, 12438, -39}, },
            {{36, 12438, -9}, },
            {{36, 95, -9}, {97, 97, 335}, {98, 12438, -90}, },
            {{36, 109, -106}, {110, 110, 336}, {111, 12438, -38}, },
            {{36, 12438, -9}, },
            {{36, 115, -25}, {116, 116, 337}, {117, 12438, -25}, },
            {{36, 12438, -9}, },
            {{36, 12438, -9}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 35, 2, 2, 2, 2, 35, 31, 22, 23, 20, 18, 30, 19, 35, 21, 32, 29, 28, 17, 16, 17, 31, 31, 26, 35, 27, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 24, 25, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 34, 34, -1, 17, 31, 31, 31, 31, 31, 31, -1, 32, 33, -1, -1, 33, 17, 17, 17, 31, 34, 34, 31, 31, 31, 31, 31, 31, 31, 31, 31, 8, 31, 31, 31, 31, 31, 31, 10, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 10, 31, -1, 33, 33, -1, -1, -1, 0, 33, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 7, 31, 31, 31, 13, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 10, 9, 3, 31, 31, 31, 31, 31, 14, 11, 6, 12, 31, -1, 33, -1, 1, 31, 9, 31, 31, 31, 4, 15, 8, 31, 31, 11, 31, 14, 31, 31, 10, 31, 31, 3, 31, 31, 31, 31, 31, 31, 12, 12, 31, 31, 6, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 4, 31, 31, 6, 31, 31, 4, 8, 13, 5, 15, -1, -1, 31, 31, 13, 31, 3, 31, 14, 6, 31, 8, 31, 31, 31, 31, 31, 31, 31, 31, 10, 31, 31, 5, 31, 31, 13, 31, 31, 31, 5, 31, 7, 12, 9, 7, 15, 14, 31, 3, 11, 7, 6, 4, 3, 31, 8, 11, 31, 9, 31, 31, 4, 31, 11, 5, 31, 9, 31, 31, 31, 31, 5, 15, 31, 31, 31, 31, 31, 15, 31, 31, 7, 31, 14, 13, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
