/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura.node;

import sakura.analysis.*;

public final class TAida extends Token
{
    public TAida()
    {
        super.setText("aida");
    }

    public TAida(int line, int pos)
    {
        super.setText("aida");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TAida(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAida(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TAida text.");
    }
}
