/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura.node;

import sakura.analysis.*;

public final class THana extends Token
{
    public THana()
    {
        super.setText("hana");
    }

    public THana(int line, int pos)
    {
        super.setText("hana");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new THana(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHana(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change THana text.");
    }
}
