/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura.node;

import sakura.analysis.*;

public final class TSeisu extends Token
{
    public TSeisu()
    {
        super.setText("seisu");
    }

    public TSeisu(int line, int pos)
    {
        super.setText("seisu");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSeisu(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSeisu(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSeisu text.");
    }
}
