/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura.node;

import sakura.analysis.*;

public final class TSoretomo extends Token
{
    public TSoretomo()
    {
        super.setText("soretomo");
    }

    public TSoretomo(int line, int pos)
    {
        super.setText("soretomo");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSoretomo(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSoretomo(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSoretomo text.");
    }
}
