/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura.node;

import sakura.analysis.*;

public final class TTame extends Token
{
    public TTame()
    {
        super.setText("tame");
    }

    public TTame(int line, int pos)
    {
        super.setText("tame");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TTame(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTame(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TTame text.");
    }
}
