/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura_jav.node;

import sakura_jav.analysis.*;

public final class TEnd extends Token
{
    public TEnd()
    {
        super.setText("rampung");
    }

    public TEnd(int line, int pos)
    {
        super.setText("rampung");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TEnd(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEnd(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TEnd text.");
    }
}
