/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura_jav.node;

import sakura_jav.analysis.*;

public final class TGe extends Token
{
    public TGe()
    {
        super.setText(">=");
    }

    public TGe(int line, int pos)
    {
        super.setText(">=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TGe(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGe(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TGe text.");
    }
}
