/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura_jav.node;

import sakura_jav.analysis.*;

public final class TJissuu extends Token
{
    public TJissuu()
    {
        super.setText("ambang");
    }

    public TJissuu(int line, int pos)
    {
        super.setText("ambang");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TJissuu(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTJissuu(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TJissuu text.");
    }
}
