/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura_jav.node;

import sakura_jav.analysis.*;

public final class TSakura extends Token
{
    public TSakura()
    {
        super.setText("sakura");
    }

    public TSakura(int line, int pos)
    {
        super.setText("sakura");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSakura(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSakura(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSakura text.");
    }
}
