/* This file was generated by SableCC (http://www.sablecc.org/). */

package sakura_jav.node;

import sakura_jav.analysis.*;

public final class TSemi extends Token
{
    public TSemi()
    {
        super.setText(";");
    }

    public TSemi(int line, int pos)
    {
        super.setText(";");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSemi(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSemi(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSemi text.");
    }
}
