/* This file was generated by SableCC (http://www.sablecc.org/). */

package Manusiaberbahasa.node;

import Manusiaberbahasa.analysis.*;

public final class TFloatLiteral extends Token
{
    public TFloatLiteral(String text)
    {
        setText(text);
    }

    public TFloatLiteral(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TFloatLiteral(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFloatLiteral(this);
    }
}
